In [1]:
import pandera.polars as pa
import numpy as np
from pathlib import Path
import polars as pl

In [2]:
def LengthCheck(size: int) -> pa.Check:
    return pa.Check(lambda x: x.apply(len) == size, error=f'List must have length {size}')


data_datasframe_schema = pa.DataFrameSchema({
    'id': pa.Column(
        pl.UInt64,
        unique=True,
        checks=[
            pa.Check.ge(0),
        ]),
    'target': pa.Column(
        pl.UInt8,
        checks=[
            pa.Check.ge(0),
            pa.Check.le(1),
        ]),
    'OfflineElectronTriggerContainer.lhmedium': pa.Column(
        pl.Boolean,
    ),
    'OfflineElectronTriggerContainer.lhvloose': pa.Column(
        pl.Boolean,
    ),
    'TrigEMClusterContainer.eta': pa.Column(
        pl.Float32,
        checks=[
            pa.Check.ge(-2.5),
            pa.Check.le(2.5),
        ]),
    'TrigEMClusterContainer.et': pa.Column(
        pl.Float32,
        checks=[
            pa.Check.ge(0),
            pa.Check.le(1e12),
        ]),
    'TrigEMClusterContainer.ringsE': pa.Column(
        pl.List(pl.Float32),
    ),
})

In [3]:
def generate_example(n_rows: int, id_start: int = 0) -> pl.DataFrame:
    data = {
    'id': np.arange(id_start, id_start + n_rows, dtype=np.uint64),
    'target': np.random.randint(0, 2, n_rows, dtype=np.uint8),
    'OfflineElectronTriggerContainer.lhmedium': np.random.choice([True, False], n_rows),
    'OfflineElectronTriggerContainer.lhvloose': np.random.choice([True, False], n_rows),
    'TrigEMClusterContainer.eta': np.random.uniform(-2.5, 2.5, n_rows).astype(np.float32),
    'TrigEMClusterContainer.et': np.random.uniform(12e3, 100e3, n_rows).astype(np.float32),
    'TrigEMClusterContainer.ringsE': [np.random.uniform(0, 1e6, 100).tolist() for _ in range(n_rows)]
    }
    example_df = pl.DataFrame(data).with_columns(pl.col('TrigEMClusterContainer.ringsE').cast(pl.List(pl.Float32)))
    return example_df

In [4]:
output_dir = Path('..') / 'tests' / 'data' / 'test_dataset' / 'electron_ringer.parquet'
output_dir.mkdir(parents=True, exist_ok=True)

In [5]:
# Generate example data with PyArrow dtypes
n_rows = 100000
for i in range(2):
    example_df = generate_example(n_rows, id_start=i*n_rows)
    example_df.write_parquet(output_dir / f'{i:04d}.parquet')
example_df

shape: (100_000, 7)
┌────────┬────────┬────────────────┬───────────────┬───────────────┬───────────────┬───────────────┐
│ id     ┆ target ┆ OfflineElectro ┆ OfflineElectr ┆ TrigEMCluster ┆ TrigEMCluster ┆ TrigEMCluster │
│ ---    ┆ ---    ┆ nTriggerContai ┆ onTriggerCont ┆ Container.eta ┆ Container.et  ┆ Container.rin │
│ u64    ┆ u8     ┆ ne…            ┆ aine…         ┆ ---           ┆ ---           ┆ gsE           │
│        ┆        ┆ ---            ┆ ---           ┆ f32           ┆ f32           ┆ ---           │
│        ┆        ┆ bool           ┆ bool          ┆               ┆               ┆ list[f32]     │
╞════════╪════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 100000 ┆ 0      ┆ false          ┆ false         ┆ -1.748538     ┆ 29721.082031  ┆ [289146.6875, │
│        ┆        ┆                ┆               ┆               ┆               ┆ 445297.34375, │
│        ┆        ┆                ┆               ┆               ┆               ┆ … …           │
│ 100001 ┆ 0      ┆ false          ┆ true          ┆ 2.260221      ┆ 94592.5625    ┆ [406272.40625 │
│        ┆        ┆                ┆               ┆               ┆               ┆ , 610574.625, │
│        ┆        ┆                ┆               ┆               ┆               ┆ … 7…          │
│ 100002 ┆ 1      ┆ false          ┆ true          ┆ 1.154022      ┆ 69357.507812  ┆ [706931.75,   │
│        ┆        ┆                ┆               ┆               ┆               ┆ 28901.347656, │
│        ┆        ┆                ┆               ┆               ┆               ┆ … 76…         │
│ 100003 ┆ 0      ┆ true           ┆ false         ┆ -1.390526     ┆ 63887.613281  ┆ [143912.39062 │
│        ┆        ┆                ┆               ┆               ┆               ┆ 5, 134645.515 │
│        ┆        ┆                ┆               ┆               ┆               ┆ 625,…         │
│ 100004 ┆ 0      ┆ false          ┆ false         ┆ -2.432841     ┆ 61345.820312  ┆ [703203.0,    │
│        ┆        ┆                ┆               ┆               ┆               ┆ 457399.03125, │
│        ┆        ┆                ┆               ┆               ┆               ┆ … 346…        │
│ …      ┆ …      ┆ …              ┆ …             ┆ …             ┆ …             ┆ …             │
│ 199995 ┆ 0      ┆ false          ┆ false         ┆ 0.169625      ┆ 95067.390625  ┆ [794640.6875, │
│        ┆        ┆                ┆               ┆               ┆               ┆ 9008.082031,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ … 7…          │
│ 199996 ┆ 1      ┆ false          ┆ false         ┆ 2.252737      ┆ 45182.511719  ┆ [395532.40625 │
│        ┆        ┆                ┆               ┆               ┆               ┆ ,             │
│        ┆        ┆                ┆               ┆               ┆               ┆ 247247.15625, │
│        ┆        ┆                ┆               ┆               ┆               ┆ ……            │
│ 199997 ┆ 0      ┆ true           ┆ true          ┆ 2.287133      ┆ 40848.5       ┆ [386631.84375 │
│        ┆        ┆                ┆               ┆               ┆               ┆ ,             │
│        ┆        ┆                ┆               ┆               ┆               ┆ 465060.9375,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ … …           │
│ 199998 ┆ 0      ┆ false          ┆ true          ┆ -2.260973     ┆ 27527.707031  ┆ [522023.625,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ 46570.65625,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ … 60…         │
│ 199999 ┆ 0      ┆ false          ┆ false         ┆ -0.339463     ┆ 86094.226562  ┆ [562986.1875, │
│        ┆        ┆                ┆               ┆               ┆               ┆ 422365.90625, │
│        ┆        ┆                ┆               ┆               ┆               ┆ … …           │
└────────┴────────┴────────────────┴───────────────┴───────────────┴───────────────┴───────────────┘

In [6]:
df = pl.read_parquet(
    '../tests/data/test_dataset/electron_ringer.parquet'
)

In [7]:
data_datasframe_schema.validate(df)

shape: (200_000, 7)
┌────────┬────────┬────────────────┬───────────────┬───────────────┬───────────────┬───────────────┐
│ id     ┆ target ┆ OfflineElectro ┆ OfflineElectr ┆ TrigEMCluster ┆ TrigEMCluster ┆ TrigEMCluster │
│ ---    ┆ ---    ┆ nTriggerContai ┆ onTriggerCont ┆ Container.eta ┆ Container.et  ┆ Container.rin │
│ u64    ┆ u8     ┆ ne…            ┆ aine…         ┆ ---           ┆ ---           ┆ gsE           │
│        ┆        ┆ ---            ┆ ---           ┆ f32           ┆ f32           ┆ ---           │
│        ┆        ┆ bool           ┆ bool          ┆               ┆               ┆ list[f32]     │
╞════════╪════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 0      ┆ 0      ┆ false          ┆ false         ┆ -0.040649     ┆ 86566.6875    ┆ [138812.4375, │
│        ┆        ┆                ┆               ┆               ┆               ┆ 245184.9375,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ … 8…          │
│ 1      ┆ 0      ┆ true           ┆ false         ┆ 1.343226      ┆ 56607.734375  ┆ [916511.4375, │
│        ┆        ┆                ┆               ┆               ┆               ┆ 198649.515625 │
│        ┆        ┆                ┆               ┆               ┆               ┆ , ……          │
│ 2      ┆ 1      ┆ false          ┆ false         ┆ 2.366676      ┆ 14107.273438  ┆ [701822.5625, │
│        ┆        ┆                ┆               ┆               ┆               ┆ 760042.125, … │
│        ┆        ┆                ┆               ┆               ┆               ┆ 11…           │
│ 3      ┆ 0      ┆ false          ┆ false         ┆ -1.054934     ┆ 91434.773438  ┆ [415156.3125, │
│        ┆        ┆                ┆               ┆               ┆               ┆ 523452.125, … │
│        ┆        ┆                ┆               ┆               ┆               ┆ 98…           │
│ 4      ┆ 0      ┆ false          ┆ true          ┆ -0.985626     ┆ 90879.75      ┆ [990425.875,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ 428619.5625,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ … 17…         │
│ …      ┆ …      ┆ …              ┆ …             ┆ …             ┆ …             ┆ …             │
│ 199995 ┆ 0      ┆ false          ┆ false         ┆ 0.169625      ┆ 95067.390625  ┆ [794640.6875, │
│        ┆        ┆                ┆               ┆               ┆               ┆ 9008.082031,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ … 7…          │
│ 199996 ┆ 1      ┆ false          ┆ false         ┆ 2.252737      ┆ 45182.511719  ┆ [395532.40625 │
│        ┆        ┆                ┆               ┆               ┆               ┆ ,             │
│        ┆        ┆                ┆               ┆               ┆               ┆ 247247.15625, │
│        ┆        ┆                ┆               ┆               ┆               ┆ ……            │
│ 199997 ┆ 0      ┆ true           ┆ true          ┆ 2.287133      ┆ 40848.5       ┆ [386631.84375 │
│        ┆        ┆                ┆               ┆               ┆               ┆ ,             │
│        ┆        ┆                ┆               ┆               ┆               ┆ 465060.9375,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ … …           │
│ 199998 ┆ 0      ┆ false          ┆ true          ┆ -2.260973     ┆ 27527.707031  ┆ [522023.625,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ 46570.65625,  │
│        ┆        ┆                ┆               ┆               ┆               ┆ … 60…         │
│ 199999 ┆ 0      ┆ false          ┆ false         ┆ -0.339463     ┆ 86094.226562  ┆ [562986.1875, │
│        ┆        ┆                ┆               ┆               ┆               ┆ 422365.90625, │
│        ┆        ┆                ┆               ┆               ┆               ┆ … …           │
└────────┴────────┴────────────────┴───────────────┴───────────────┴───────────────┴───────────────┘