In [1]:
from pathlib import Path
from tempfile import TemporaryDirectory
import tarfile
import pandas as pd
import numpy as np
import duckdb
import os
import sys
sys.path.append(str(Path(os.getcwd()).parent.absolute()))
import colorlog
logger = colorlog.getLogger()

from ringer_zero.root import read_ttree_as_pdf
TTREE_NAME = 'run_410000/HLT/EgammaMon/summary/events'

In [2]:
source_files = {
    'jf17': {
        'datapath': Path(
            '/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz'
        ),
        'target': 0
    },
    'zee': {
        'datapath': Path(
            '/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_v0_EXT0.tap_zee_5M_XYZ.root.tgz'
        ),
        'target': 1
    }
}
samples_per_batch = 100000
output_dir = Path('/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/data.parquet')
if output_dir.exists():
    logger.warning(f'Output directory {output_dir} already exists. Files may be overwritten.')
else:
    output_dir.mkdir(parents=True, exist_ok=True)

 [Sun, 15 Mar 2026 22:46:34] WARNING Output directory /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/data.parquet already exists. Files may be overwritten.

In [3]:
def is_safe_int8_cast(series: pd.Series):
    unique_values = series.unique().to_numpy()
    if np.any(np.logical_and(unique_values != 0, unique_values != 1)):
        raise ValueError(f"Series must contain only 1's and 0's for int8 casting, found {unique_values}")
    return True


INT8_CASTS = [
    'el_lhtight',
    'el_lhmedium',
    'el_lhloose',
    'el_lhvloose',
    'el_dnntight',
    'el_dnnmedium',
    'el_dnnloose',
    'mc_hasMC',
    'mc_isTruthElectronAny',
    'mc_isTruthElectronFromZ',
    'mc_isTruthElectronFromJpsiPrompt'
]

def dump_df(df, file_count, processed_rows, output_dir):
    logger.info(f'Processing Batch {file_count} (Rows {processed_rows} to {processed_rows + len(df)})')
    output_path = output_dir / f'data_{file_count:04d}.parquet'
    df['id'] = pd.Series(range(processed_rows, processed_rows + len(df)), dtype="uint64[pyarrow]")
    for col in INT8_CASTS:
        is_safe_int8_cast(df[col])
        df[col] = df[col].astype('bool[pyarrow]')
    df.to_parquet(output_path, index=False)
    return file_count + 1, processed_rows + len(df)

In [4]:
df_accumulator = pd.DataFrame()
file_count = 0
processed_rows = 0

for sample_name, sample_info in source_files.items():
    for root_tar in sample_info['datapath'].glob('*.root.tgz'):
        logger.info(f'Reading {root_tar} for sample {sample_name}')
        with TemporaryDirectory() as temp_dir:
            temp_dir_path = Path(temp_dir)
            with tarfile.open(root_tar, 'r:gz') as tar:
                tar.extractall(path=temp_dir_path)
            for root_file in temp_dir_path.glob('*.root'):
                logger.info(f'Reading {root_file} for sample {sample_name}')
                df = read_ttree_as_pdf(root_file, ttree_name='run_410000/HLT/EgammaMon/summary/events')
                df['target'] = sample_info['target']
                df['target'] = df['target'].astype('uint8[pyarrow]')
                df_accumulator = pd.concat([df_accumulator, df], ignore_index=True)
                if len(df_accumulator) >= samples_per_batch:
                    file_count, processed_rows = dump_df(
                        df_accumulator, file_count, processed_rows, output_dir
                    )
                    df_accumulator = pd.DataFrame()  # Reset accumulator

if len(df_accumulator):
    file_count, processed_rows = dump_df(
        df_accumulator, file_count, processed_rows, output_dir
    )

 [Sun, 15 Mar 2026 22:46:36] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000001.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:36] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000002.root for sample jf17
 [Sun, 15 Mar 2026 22:46:36] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000010.root for sample jf17
 [Sun, 15 Mar 2026 22:46:37] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000004.root for sample jf17
 [Sun, 15 Mar 2026 22:46:37] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000009.root for sample jf17
 [Sun, 15 Mar 2026 22:46:37] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000008.root for sample jf17
 [Sun, 15 Mar 2026 22:46:38] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000006.root for sample jf17
 [Sun, 15 Mar 2026 22:46:38] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000007.root for sample jf17
 [Sun, 15 Mar 2026 22:46:38] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000001.root for sample jf17
 [Sun, 15 Mar 2026 22:46:38] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000003.root for sample jf17
 [Sun, 15 Mar 2026 22:46:39] INFO Reading /tmp/tmpm7lak3e0/output.35450371._000005.root for sample jf17
 [Sun, 15 Mar 2026 22:46:39] INFO Processing Batch 0 (Rows 0 to 102182)
 [Sun, 15 Mar 2026 22:46:40] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000002.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:40] INFO Reading /tmp/tmpj0ahvby_/output.35450371._000501.root for sample jf17
 [Sun, 15 Mar 2026 22:46:40] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000003.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:40] INFO Reading /tmp/tmpnoop1qyj/output.35450371._000491.root for sample jf17
 [Sun, 15 Mar 2026 22:46:41] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000004.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:41] INFO Reading /tmp/tmp84u6e4te/output.35450371._000215.root for sample jf17
 [Sun, 15 Mar 2026 22:46:41] INFO Reading /tmp/tmp84u6e4te/output.35450371._000219.root for sample jf17
 [Sun, 15 Mar 2026 22:46:41] INFO Reading /tmp/tmp84u6e4te/output.35450371._000216.root for sample jf17
 [Sun, 15 Mar 2026 22:46:42] INFO Reading /tmp/tmp84u6e4te/output.35450371._000217.root for sample jf17
 [Sun, 15 Mar 2026 22:46:42] INFO Reading /tmp/tmp84u6e4te/output.35450371._000220.root for sample jf17
 [Sun, 15 Mar 2026 22:46:42] INFO Reading /tmp/tmp84u6e4te/output.35450371._000218.root for sample jf17
 [Sun, 15 Mar 2026 22:46:43] INFO Reading /tmp/tmp84u6e4te/output.35450371._000222.root for sample jf17
 [Sun, 15 Mar 2026 22:46:43] INFO Reading /tmp/tmp84u6e4te/output.35450371._000221.root for sample jf17
 [Sun, 15 Mar 2026 22:46:43] INFO Processing Batch 1 (Rows 102182 to 204094)
 [Sun, 15 Mar 2026 22:46:44] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000007.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:45] INFO Reading /tmp/tmp76533fu4/output.35450371._000081.root for sample jf17
 [Sun, 15 Mar 2026 22:46:45] INFO Reading /tmp/tmp76533fu4/output.35450371._000066.root for sample jf17
 [Sun, 15 Mar 2026 22:46:46] INFO Reading /tmp/tmp76533fu4/output.35450371._000064.root for sample jf17
 [Sun, 15 Mar 2026 22:46:46] INFO Reading /tmp/tmp76533fu4/output.35450371._000072.root for sample jf17
 [Sun, 15 Mar 2026 22:46:46] INFO Reading /tmp/tmp76533fu4/output.35450371._000068.root for sample jf17
 [Sun, 15 Mar 2026 22:46:47] INFO Reading /tmp/tmp76533fu4/output.35450371._000074.root for sample jf17
 [Sun, 15 Mar 2026 22:46:47] INFO Reading /tmp/tmp76533fu4/output.35450371._000076.root for sample jf17
 [Sun, 15 Mar 2026 22:46:47] INFO Reading /tmp/tmp76533fu4/output.35450371._000063.root for sample jf17
 [Sun, 15 Mar 2026 22:46:47] INFO Reading /tmp/tmp76533fu4/output.35450371._000071.root for sample jf17
 [Sun, 15 Mar 2026 22:46:48] INFO Reading /tmp/tmp76533fu4/output.35450371._000065.root for sample jf17
 [Sun, 15 Mar 2026 22:46:48] INFO Processing Batch 2 (Rows 204094 to 305901)
 [Sun, 15 Mar 2026 22:46:49] INFO Reading /tmp/tmp76533fu4/output.35450371._000078.root for sample jf17
 [Sun, 15 Mar 2026 22:46:49] INFO Reading /tmp/tmp76533fu4/output.35450371._000080.root for sample jf17
 [Sun, 15 Mar 2026 22:46:50] INFO Reading /tmp/tmp76533fu4/output.35450371._000069.root for sample jf17
 [Sun, 15 Mar 2026 22:46:50] INFO Reading /tmp/tmp76533fu4/output.35450371._000062.root for sample jf17
 [Sun, 15 Mar 2026 22:46:50] INFO Reading /tmp/tmp76533fu4/output.35450371._000083.root for sample jf17
 [Sun, 15 Mar 2026 22:46:50] INFO Reading /tmp/tmp76533fu4/output.35450371._000079.root for sample jf17
 [Sun, 15 Mar 2026 22:46:51] INFO Reading /tmp/tmp76533fu4/output.35450371._000077.root for sample jf17
 [Sun, 15 Mar 2026 22:46:51] INFO Reading /tmp/tmp76533fu4/output.35450371._000061.root for sample jf17
 [Sun, 15 Mar 2026 22:46:51] INFO Reading /tmp/tmp76533fu4/output.35450371._000070.root for sample jf17
 [Sun, 15 Mar 2026 22:46:52] INFO Reading /tmp/tmp76533fu4/output.35450371._000075.root for sample jf17
 [Sun, 15 Mar 2026 22:46:52] INFO Processing Batch 3 (Rows 305901 to 407451)
 [Sun, 15 Mar 2026 22:46:53] INFO Reading /tmp/tmp76533fu4/output.35450371._000073.root for sample jf17
 [Sun, 15 Mar 2026 22:46:53] INFO Reading /tmp/tmp76533fu4/output.35450371._000082.root for sample jf17
 [Sun, 15 Mar 2026 22:46:54] INFO Reading /tmp/tmp76533fu4/output.35450371._000067.root for sample jf17
 [Sun, 15 Mar 2026 22:46:54] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000008.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:46:55] INFO Reading /tmp/tmp7__s88mn/output.35450371._000234.root for sample jf17
 [Sun, 15 Mar 2026 22:46:55] INFO Reading /tmp/tmp7__s88mn/output.35450371._000245.root for sample jf17
 [Sun, 15 Mar 2026 22:46:56] INFO Reading /tmp/tmp7__s88mn/output.35450371._000239.root for sample jf17
 [Sun, 15 Mar 2026 22:46:56] INFO Reading /tmp/tmp7__s88mn/output.35450371._000238.root for sample jf17
 [Sun, 15 Mar 2026 22:46:56] INFO Reading /tmp/tmp7__s88mn/output.35450371._000232.root for sample jf17
 [Sun, 15 Mar 2026 22:46:57] INFO Reading /tmp/tmp7__s88mn/output.35450371._000252.root for sample jf17
 [Sun, 15 Mar 2026 22:46:57] INFO Reading /tmp/tmp7__s88mn/output.35450371._000226.root for sample jf17
 [Sun, 15 Mar 2026 22:46:57] INFO Processing Batch 4 (Rows 407451 to 508227)
 [Sun, 15 Mar 2026 22:46:58] INFO Reading /tmp/tmp7__s88mn/output.35450371._000248.root for sample jf17
 [Sun, 15 Mar 2026 22:46:58] INFO Reading /tmp/tmp7__s88mn/output.35450371._000237.root for sample jf17
 [Sun, 15 Mar 2026 22:46:59] INFO Reading /tmp/tmp7__s88mn/output.35450371._000242.root for sample jf17
 [Sun, 15 Mar 2026 22:46:59] INFO Reading /tmp/tmp7__s88mn/output.35450371._000244.root for sample jf17
 [Sun, 15 Mar 2026 22:46:59] INFO Reading /tmp/tmp7__s88mn/output.35450371._000250.root for sample jf17
 [Sun, 15 Mar 2026 22:47:00] INFO Reading /tmp/tmp7__s88mn/output.35450371._000230.root for sample jf17
 [Sun, 15 Mar 2026 22:47:00] INFO Reading /tmp/tmp7__s88mn/output.35450371._000236.root for sample jf17
 [Sun, 15 Mar 2026 22:47:00] INFO Reading /tmp/tmp7__s88mn/output.35450371._000235.root for sample jf17
 [Sun, 15 Mar 2026 22:47:01] INFO Reading /tmp/tmp7__s88mn/output.35450371._000240.root for sample jf17
 [Sun, 15 Mar 2026 22:47:01] INFO Reading /tmp/tmp7__s88mn/output.35450371._000241.root for sample jf17
 [Sun, 15 Mar 2026 22:47:01] INFO Processing Batch 5 (Rows 508227 to 609780)
 [Sun, 15 Mar 2026 22:47:02] INFO Reading /tmp/tmp7__s88mn/output.35450371._000233.root for sample jf17
 [Sun, 15 Mar 2026 22:47:03] INFO Reading /tmp/tmp7__s88mn/output.35450371._000229.root for sample jf17
 [Sun, 15 Mar 2026 22:47:03] INFO Reading /tmp/tmp7__s88mn/output.35450371._000251.root for sample jf17
 [Sun, 15 Mar 2026 22:47:03] INFO Reading /tmp/tmp7__s88mn/output.35450371._000246.root for sample jf17
 [Sun, 15 Mar 2026 22:47:04] INFO Reading /tmp/tmp7__s88mn/output.35450371._000224.root for sample jf17
 [Sun, 15 Mar 2026 22:47:04] INFO Reading /tmp/tmp7__s88mn/output.35450371._000247.root for sample jf17
 [Sun, 15 Mar 2026 22:47:04] INFO Reading /tmp/tmp7__s88mn/output.35450371._000223.root for sample jf17
 [Sun, 15 Mar 2026 22:47:05] INFO Reading /tmp/tmp7__s88mn/output.35450371._000225.root for sample jf17
 [Sun, 15 Mar 2026 22:47:05] INFO Reading /tmp/tmp7__s88mn/output.35450371._000227.root for sample jf17
 [Sun, 15 Mar 2026 22:47:05] INFO Reading /tmp/tmp7__s88mn/output.35450371._000231.root for sample jf17
 [Sun, 15 Mar 2026 22:47:06] INFO Processing Batch 6 (Rows 609780 to 710888)
 [Sun, 15 Mar 2026 22:47:07] INFO Reading /tmp/tmp7__s88mn/output.35450371._000243.root for sample jf17
 [Sun, 15 Mar 2026 22:47:07] INFO Reading /tmp/tmp7__s88mn/output.35450371._000228.root for sample jf17
 [Sun, 15 Mar 2026 22:47:07] INFO Reading /tmp/tmp7__s88mn/output.35450371._000249.root for sample jf17
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000009.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /tmp/tmpjqafoyum/output.35450371._000610.root for sample jf17
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000010.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /tmp/tmpd70mo96v/output.35450371._000611.root for sample jf17
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000011.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:47:08] INFO Reading /tmp/tmpjiyq3lti/output.35450371._000613.root for sample jf17
 [Sun, 15 Mar 2026 22:47:09] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000012.XYZ.root.tgz for sample jf17
/tmp/ipykernel_1094136/3714514901.py:11: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 22:47:11] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000053.root for sample jf17
 [Sun, 15 Mar 2026 22:47:11] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000049.root for sample jf17
 [Sun, 15 Mar 2026 22:47:12] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000047.root for sample jf17
 [Sun, 15 Mar 2026 22:47:12] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000041.root for sample jf17
 [Sun, 15 Mar 2026 22:47:12] INFO Processing Batch 7 (Rows 710888 to 812912)
 [Sun, 15 Mar 2026 22:47:13] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000016.root for sample jf17
 [Sun, 15 Mar 2026 22:47:14] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000013.root for sample jf17
 [Sun, 15 Mar 2026 22:47:14] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000019.root for sample jf17
 [Sun, 15 Mar 2026 22:47:14] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000031.root for sample jf17
 [Sun, 15 Mar 2026 22:47:15] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000030.root for sample jf17
 [Sun, 15 Mar 2026 22:47:15] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000043.root for sample jf17
 [Sun, 15 Mar 2026 22:47:15] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000056.root for sample jf17
 [Sun, 15 Mar 2026 22:47:15] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000059.root for sample jf17
 [Sun, 15 Mar 2026 22:47:16] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000050.root for sample jf17
 [Sun, 15 Mar 2026 22:47:16] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000023.root for sample jf17
 [Sun, 15 Mar 2026 22:47:16] INFO Processing Batch 8 (Rows 812912 to 914829)
 [Sun, 15 Mar 2026 22:47:17] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000011.root for sample jf17
 [Sun, 15 Mar 2026 22:47:18] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000021.root for sample jf17
 [Sun, 15 Mar 2026 22:47:18] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000045.root for sample jf17
 [Sun, 15 Mar 2026 22:47:18] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000015.root for sample jf17
 [Sun, 15 Mar 2026 22:47:18] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000042.root for sample jf17
 [Sun, 15 Mar 2026 22:47:19] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000033.root for sample jf17
 [Sun, 15 Mar 2026 22:47:19] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000018.root for sample jf17
 [Sun, 15 Mar 2026 22:47:19] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000024.root for sample jf17
 [Sun, 15 Mar 2026 22:47:20] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000060.root for sample jf17
 [Sun, 15 Mar 2026 22:47:20] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000052.root for sample jf17
 [Sun, 15 Mar 2026 22:47:20] INFO Processing Batch 9 (Rows 914829 to 1016502)
 [Sun, 15 Mar 2026 22:47:21] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000035.root for sample jf17
 [Sun, 15 Mar 2026 22:47:22] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000039.root for sample jf17
 [Sun, 15 Mar 2026 22:47:22] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000051.root for sample jf17
 [Sun, 15 Mar 2026 22:47:22] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000029.root for sample jf17
 [Sun, 15 Mar 2026 22:47:22] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000054.root for sample jf17
 [Sun, 15 Mar 2026 22:47:23] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000014.root for sample jf17
 [Sun, 15 Mar 2026 22:47:23] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000034.root for sample jf17
 [Sun, 15 Mar 2026 22:47:23] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000025.root for sample jf17
 [Sun, 15 Mar 2026 22:47:24] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000032.root for sample jf17
 [Sun, 15 Mar 2026 22:47:24] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000040.root for sample jf17
 [Sun, 15 Mar 2026 22:47:24] INFO Processing Batch 10 (Rows 1016502 to 1118291)
 [Sun, 15 Mar 2026 22:47:25] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000044.root for sample jf17
 [Sun, 15 Mar 2026 22:47:25] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000036.root for sample jf17
 [Sun, 15 Mar 2026 22:47:26] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000017.root for sample jf17
 [Sun, 15 Mar 2026 22:47:26] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000046.root for sample jf17
 [Sun, 15 Mar 2026 22:47:26] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000020.root for sample jf17
 [Sun, 15 Mar 2026 22:47:27] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000058.root for sample jf17
 [Sun, 15 Mar 2026 22:47:27] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000027.root for sample jf17
 [Sun, 15 Mar 2026 22:47:27] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000026.root for sample jf17
 [Sun, 15 Mar 2026 22:47:28] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000048.root for sample jf17
 [Sun, 15 Mar 2026 22:47:28] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000037.root for sample jf17
 [Sun, 15 Mar 2026 22:47:28] INFO Processing Batch 11 (Rows 1118291 to 1220335)
 [Sun, 15 Mar 2026 22:47:29] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000028.root for sample jf17
 [Sun, 15 Mar 2026 22:47:30] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000038.root for sample jf17
 [Sun, 15 Mar 2026 22:47:30] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000012.root for sample jf17
 [Sun, 15 Mar 2026 22:47:30] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000055.root for sample jf17
 [Sun, 15 Mar 2026 22:47:30] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000022.root for sample jf17
 [Sun, 15 Mar 2026 22:47:31] INFO Reading /tmp/tmpbjf7ei0k/output.35450371._000057.root for sample jf17
 [Sun, 15 Mar 2026 22:47:31] INFO Reading /media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/source/bkg/user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_without_sigma_constraint_31.10.23_v0_EXT0.tap_jf17_5M_XYZ.root.tgz/user.isilvafe.35450371._000014.XYZ.root.tgz for sample jf17

# Validate Dataset

In [5]:
output_path_glob = output_dir / 'data_*.parquet'
print(str(output_path_glob))

/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/data.parquet/data_*.parquet

## Check Target

In [6]:
target_query = f"""
SELECT
    COALESCE(CAST(target AS VARCHAR), 'NULL') AS value,
    COUNT(*) as count
FROM read_parquet('{str(output_path_glob)}')
GROUP BY target
ORDER BY target ASC;
"""
print(target_query)

SELECT
    COALESCE(CAST(target AS VARCHAR), 'NULL') AS value,
    COUNT(*) as count
FROM read_parquet('/media/lucasbanunes/KINGSTON/data/cern-datasets/mc21_isabela_qt_no_restriction/data.parquet/data_*.parquet')
GROUP BY target
ORDER BY target ASC;

In [7]:
with duckdb.connect(':memory:') as conn:
    df = conn.execute(target_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
# df.value_counts(dropna=False)
df

  value    count
0     0  4988951
1     1  2177107

## Check ID

In [8]:
id_query = f"""
SELECT
    COALESCE(CAST(id AS VARCHAR), 'NULL') AS value,
    COUNT(*) as count
FROM read_parquet('{str(output_path_glob)}')
GROUP BY id
ORDER BY id ASC;
"""

In [12]:
with duckdb.connect(':memory:') as conn:
    df = conn.execute(id_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
# df.value_counts(dropna=False)
df

           value  count
0              0      1
1              1      1
2              2      1
3              3      1
4              4      1
...          ...    ...
7166053  7166053      1
7166054  7166054      1
7166055  7166055      1
7166056  7166056      1
7166057  7166057      1

[7166058 rows x 2 columns]

In [13]:
df[df['count'] != 1]

Empty DataFrame
Columns: [value, count]
Index: []