In [12]:
from pathlib import Path
from tempfile import TemporaryDirectory
import tarfile
import pandas as pd
import awkward as ak
import ROOT
import pyarrow as pa
import numpy as np
import duckdb
import os
import sys
sys.path.append(str(Path(os.getcwd()).parent.absolute()))
import colorlog
logger = colorlog.getLogger()

from ringer_zero.root import read_ttree_as_pdf

In [2]:
TTREE_NAME = 'run_410000/HLT/EgammaMon/summary/events'

In [3]:
source_files = {
    'jf17': {
        'datapath': Path(
            '/media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz'
        ),
        'target': 1
    },
    'zee': {
        'datapath': Path(
            '/media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz'
        ),
        'target': 0
    }
}
samples_per_batch = 100000
output_dir = Path('/media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/data.parquet')
output_dir.mkdir(parents=True, exist_ok=True)

In [ ]:
def is_safe_int8_cast(series: pd.Series):
    unique_values = series.unique().to_numpy()
    if np.any(np.logical_and(unique_values != 0, unique_values != 1)):
        raise ValueError(f"Series must contain only 1's and 0's for int8 casting, found {unique_values}")
    return True


INT8_CASTS = [
    'el_lhtight',
    'el_lhmedium',
    'el_lhloose',
    'el_lhvloose',
    'el_dnntight',
    'el_dnnmedium',
    'el_dnnloose',
    'mc_hasMC',
    'mc_isTruthElectronAny',
    'mc_isTruthElectronFromZ',
    'mc_isTruthElectronFromJpsiPrompt'
]

def dump_df(df, file_count, processed_rows, output_dir):
    logger.info(f'Processing Batch {file_count} (Rows {processed_rows} to {processed_rows + len(df)})')
    output_path = output_dir / f'data_{file_count:04d}.parquet'
    df['id'] = pd.Series(range(processed_rows, processed_rows + len(df)), dtype="uint64[pyarrow]")
    for col in INT8_CASTS:
        is_safe_int8_cast(df[col])
        df[col] = df[col].astype('bool[pyarrow]')
    df.to_parquet(output_path, index=False)
    return file_count + 1, processed_rows + len(df)

In [5]:
df_accumulator = pd.DataFrame()
file_count = 0
processed_rows = 0

for sample_name, sample_info in source_files.items():
    for root_tar in sample_info['datapath'].glob('*.root.tgz'):
        logger.info(f'Reading {root_tar} for sample {sample_name}')
        with TemporaryDirectory() as temp_dir:
            temp_dir_path = Path(temp_dir)
            with tarfile.open(root_tar, 'r:gz') as tar:
                tar.extractall(path=temp_dir_path)
            for root_file in temp_dir_path.glob('*.root'):
                logger.info(f'Reading {root_file} for sample {sample_name}')
                df = read_ttree_as_pdf(root_file, ttree_name='run_410000/HLT/EgammaMon/summary/events')
                df['target'] = sample_info['target']
                df['target'] = df['target'].astype('uint8[pyarrow]')
                df_accumulator = pd.concat([df_accumulator, df], ignore_index=True)
                if len(df_accumulator) >= samples_per_batch:
                    file_count, processed_rows = dump_df(
                        df_accumulator, file_count, processed_rows, output_dir
                    )
                    df_accumulator = pd.DataFrame()  # Reset accumulator

if len(df_accumulator):
    file_count, processed_rows = dump_df(
        df_accumulator, file_count, processed_rows, output_dir
    )

 [Sun, 15 Mar 2026 21:04:11] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000001.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:11] INFO Reading /tmp/tmp3a5jceip/output.35439386._000003.root for sample jf17
 [Sun, 15 Mar 2026 21:04:11] INFO Reading /tmp/tmp3a5jceip/output.35439386._000004.root for sample jf17
 [Sun, 15 Mar 2026 21:04:11] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000002.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:12] INFO Reading /tmp/tmpra5qc7vg/output.35439386._000008.root for sample jf17
 [Sun, 15 Mar 2026 21:04:12] INFO Reading /tmp/tmpra5qc7vg/output.35439386._000007.root for sample jf17
 [Sun, 15 Mar 2026 21:04:12] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000003.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:12] INFO Reading /tmp/tmp3nxoe1ia/output.35439386._000005.root for sample jf17
 [Sun, 15 Mar 2026 21:04:13] INFO Reading /tmp/tmp3nxoe1ia/output.35439386._000006.root for sample jf17
 [Sun, 15 Mar 2026 21:04:13] INFO Reading /tmp/tmp3nxoe1ia/output.35439386._000010.root for sample jf17
 [Sun, 15 Mar 2026 21:04:13] INFO Reading /tmp/tmp3nxoe1ia/output.35439386._000009.root for sample jf17
 [Sun, 15 Mar 2026 21:04:13] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000004.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:14] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000291.root for sample jf17
 [Sun, 15 Mar 2026 21:04:14] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000287.root for sample jf17

Processing Batch 0 (Rows 0 to 101869)

 [Sun, 15 Mar 2026 21:04:16] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000301.root for sample jf17
 [Sun, 15 Mar 2026 21:04:16] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000295.root for sample jf17
 [Sun, 15 Mar 2026 21:04:16] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000294.root for sample jf17
 [Sun, 15 Mar 2026 21:04:16] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000282.root for sample jf17
 [Sun, 15 Mar 2026 21:04:17] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000298.root for sample jf17
 [Sun, 15 Mar 2026 21:04:17] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000299.root for sample jf17
 [Sun, 15 Mar 2026 21:04:17] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000285.root for sample jf17
 [Sun, 15 Mar 2026 21:04:17] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000281.root for sample jf17
 [Sun, 15 Mar 2026 21:04:18] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000300.root for sample jf17
 [Sun, 15 Mar 2026 21:04:18] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000283.root for sample jf17

Processing Batch 1 (Rows 101869 to 203423)

 [Sun, 15 Mar 2026 21:04:19] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000280.root for sample jf17
 [Sun, 15 Mar 2026 21:04:19] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000289.root for sample jf17
 [Sun, 15 Mar 2026 21:04:20] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000297.root for sample jf17
 [Sun, 15 Mar 2026 21:04:20] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000279.root for sample jf17
 [Sun, 15 Mar 2026 21:04:20] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000278.root for sample jf17
 [Sun, 15 Mar 2026 21:04:20] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000286.root for sample jf17
 [Sun, 15 Mar 2026 21:04:21] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000292.root for sample jf17
 [Sun, 15 Mar 2026 21:04:21] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000288.root for sample jf17
 [Sun, 15 Mar 2026 21:04:21] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000284.root for sample jf17
 [Sun, 15 Mar 2026 21:04:21] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000302.root for sample jf17

Processing Batch 2 (Rows 203423 to 305105)

 [Sun, 15 Mar 2026 21:04:23] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000293.root for sample jf17
 [Sun, 15 Mar 2026 21:04:23] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000296.root for sample jf17
 [Sun, 15 Mar 2026 21:04:23] INFO Reading /tmp/tmp5wb3xo51/output.35439386._000290.root for sample jf17
 [Sun, 15 Mar 2026 21:04:23] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000005.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:23] INFO Reading /tmp/tmp_x1h6heq/output.35439386._000143.root for sample jf17
 [Sun, 15 Mar 2026 21:04:24] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000006.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:24] INFO Reading /tmp/tmpmp9sq5cw/output.35439386._000140.root for sample jf17
 [Sun, 15 Mar 2026 21:04:24] INFO Reading /tmp/tmpmp9sq5cw/output.35439386._000141.root for sample jf17
 [Sun, 15 Mar 2026 21:04:24] INFO Reading /tmp/tmpmp9sq5cw/output.35439386._000142.root for sample jf17
 [Sun, 15 Mar 2026 21:04:25] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000007.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:25] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000472.root for sample jf17
 [Sun, 15 Mar 2026 21:04:26] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000453.root for sample jf17
 [Sun, 15 Mar 2026 21:04:26] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000464.root for sample jf17

Processing Batch 3 (Rows 305105 to 406992)

 [Sun, 15 Mar 2026 21:04:27] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000462.root for sample jf17
 [Sun, 15 Mar 2026 21:04:27] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000460.root for sample jf17
 [Sun, 15 Mar 2026 21:04:28] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000448.root for sample jf17
 [Sun, 15 Mar 2026 21:04:28] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000454.root for sample jf17
 [Sun, 15 Mar 2026 21:04:28] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000468.root for sample jf17
 [Sun, 15 Mar 2026 21:04:28] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000466.root for sample jf17
 [Sun, 15 Mar 2026 21:04:29] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000465.root for sample jf17
 [Sun, 15 Mar 2026 21:04:29] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000449.root for sample jf17
 [Sun, 15 Mar 2026 21:04:29] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000470.root for sample jf17
 [Sun, 15 Mar 2026 21:04:29] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000469.root for sample jf17

Processing Batch 4 (Rows 406992 to 508597)

 [Sun, 15 Mar 2026 21:04:31] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000463.root for sample jf17
 [Sun, 15 Mar 2026 21:04:31] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000471.root for sample jf17
 [Sun, 15 Mar 2026 21:04:31] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000459.root for sample jf17
 [Sun, 15 Mar 2026 21:04:31] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000456.root for sample jf17
 [Sun, 15 Mar 2026 21:04:32] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000451.root for sample jf17
 [Sun, 15 Mar 2026 21:04:32] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000452.root for sample jf17
 [Sun, 15 Mar 2026 21:04:32] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000455.root for sample jf17
 [Sun, 15 Mar 2026 21:04:33] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000457.root for sample jf17
 [Sun, 15 Mar 2026 21:04:33] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000458.root for sample jf17
 [Sun, 15 Mar 2026 21:04:33] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000461.root for sample jf17

Processing Batch 5 (Rows 508597 to 610571)

 [Sun, 15 Mar 2026 21:04:34] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000467.root for sample jf17
 [Sun, 15 Mar 2026 21:04:34] INFO Reading /tmp/tmp8x5aqfex/output.35439386._000450.root for sample jf17
 [Sun, 15 Mar 2026 21:04:35] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000008.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:35] INFO Reading /tmp/tmp4g0jwoiq/output.35439386._000001.root for sample jf17
 [Sun, 15 Mar 2026 21:04:35] INFO Reading /tmp/tmp4g0jwoiq/output.35439386._000002.root for sample jf17
 [Sun, 15 Mar 2026 21:04:35] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000009.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:36] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000151.root for sample jf17
 [Sun, 15 Mar 2026 21:04:36] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000147.root for sample jf17
 [Sun, 15 Mar 2026 21:04:36] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000146.root for sample jf17
 [Sun, 15 Mar 2026 21:04:37] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000150.root for sample jf17
 [Sun, 15 Mar 2026 21:04:37] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000153.root for sample jf17
 [Sun, 15 Mar 2026 21:04:37] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000154.root for sample jf17

Processing Batch 6 (Rows 610571 to 712795)

 [Sun, 15 Mar 2026 21:04:38] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000152.root for sample jf17
 [Sun, 15 Mar 2026 21:04:39] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000149.root for sample jf17
 [Sun, 15 Mar 2026 21:04:39] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000144.root for sample jf17
 [Sun, 15 Mar 2026 21:04:39] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000148.root for sample jf17
 [Sun, 15 Mar 2026 21:04:39] INFO Reading /tmp/tmp0g1rktj3/output.35439386._000145.root for sample jf17
 [Sun, 15 Mar 2026 21:04:40] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000010.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:40] INFO Reading /tmp/tmpu8566d5c/output.35439386._000333.root for sample jf17
 [Sun, 15 Mar 2026 21:04:41] INFO Reading /tmp/tmpu8566d5c/output.35439386._000336.root for sample jf17
 [Sun, 15 Mar 2026 21:04:41] INFO Reading /tmp/tmpu8566d5c/output.35439386._000358.root for sample jf17
 [Sun, 15 Mar 2026 21:04:41] INFO Reading /tmp/tmpu8566d5c/output.35439386._000353.root for sample jf17
 [Sun, 15 Mar 2026 21:04:42] INFO Reading /tmp/tmpu8566d5c/output.35439386._000334.root for sample jf17

Processing Batch 7 (Rows 712795 to 814630)

 [Sun, 15 Mar 2026 21:04:43] INFO Reading /tmp/tmpu8566d5c/output.35439386._000355.root for sample jf17
 [Sun, 15 Mar 2026 21:04:43] INFO Reading /tmp/tmpu8566d5c/output.35439386._000361.root for sample jf17
 [Sun, 15 Mar 2026 21:04:43] INFO Reading /tmp/tmpu8566d5c/output.35439386._000342.root for sample jf17
 [Sun, 15 Mar 2026 21:04:44] INFO Reading /tmp/tmpu8566d5c/output.35439386._000359.root for sample jf17
 [Sun, 15 Mar 2026 21:04:44] INFO Reading /tmp/tmpu8566d5c/output.35439386._000346.root for sample jf17
 [Sun, 15 Mar 2026 21:04:44] INFO Reading /tmp/tmpu8566d5c/output.35439386._000362.root for sample jf17
 [Sun, 15 Mar 2026 21:04:44] INFO Reading /tmp/tmpu8566d5c/output.35439386._000337.root for sample jf17
 [Sun, 15 Mar 2026 21:04:45] INFO Reading /tmp/tmpu8566d5c/output.35439386._000340.root for sample jf17
 [Sun, 15 Mar 2026 21:04:45] INFO Reading /tmp/tmpu8566d5c/output.35439386._000330.root for sample jf17
 [Sun, 15 Mar 2026 21:04:45] INFO Reading /tmp/tmpu8566d5c/output.35439386._000328.root for sample jf17

Processing Batch 8 (Rows 814630 to 916206)

 [Sun, 15 Mar 2026 21:04:47] INFO Reading /tmp/tmpu8566d5c/output.35439386._000329.root for sample jf17
 [Sun, 15 Mar 2026 21:04:47] INFO Reading /tmp/tmpu8566d5c/output.35439386._000363.root for sample jf17
 [Sun, 15 Mar 2026 21:04:47] INFO Reading /tmp/tmpu8566d5c/output.35439386._000352.root for sample jf17
 [Sun, 15 Mar 2026 21:04:47] INFO Reading /tmp/tmpu8566d5c/output.35439386._000357.root for sample jf17
 [Sun, 15 Mar 2026 21:04:48] INFO Reading /tmp/tmpu8566d5c/output.35439386._000338.root for sample jf17
 [Sun, 15 Mar 2026 21:04:48] INFO Reading /tmp/tmpu8566d5c/output.35439386._000344.root for sample jf17
 [Sun, 15 Mar 2026 21:04:48] INFO Reading /tmp/tmpu8566d5c/output.35439386._000351.root for sample jf17
 [Sun, 15 Mar 2026 21:04:49] INFO Reading /tmp/tmpu8566d5c/output.35439386._000349.root for sample jf17
 [Sun, 15 Mar 2026 21:04:49] INFO Reading /tmp/tmpu8566d5c/output.35439386._000354.root for sample jf17
 [Sun, 15 Mar 2026 21:04:49] INFO Reading /tmp/tmpu8566d5c/output.35439386._000343.root for sample jf17

Processing Batch 9 (Rows 916206 to 1017495)

 [Sun, 15 Mar 2026 21:04:50] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000011.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:51] INFO Reading /tmp/tmptwrlazcw/output.35439386._000498.root for sample jf17
 [Sun, 15 Mar 2026 21:04:51] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000012.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:04:53] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000047.root for sample jf17
 [Sun, 15 Mar 2026 21:04:53] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000038.root for sample jf17
 [Sun, 15 Mar 2026 21:04:53] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000020.root for sample jf17
 [Sun, 15 Mar 2026 21:04:53] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000019.root for sample jf17
 [Sun, 15 Mar 2026 21:04:54] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000055.root for sample jf17
 [Sun, 15 Mar 2026 21:04:54] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000057.root for sample jf17
 [Sun, 15 Mar 2026 21:04:54] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000041.root for sample jf17
 [Sun, 15 Mar 2026 21:04:55] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000049.root for sample jf17
 [Sun, 15 Mar 2026 21:04:55] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000029.root for sample jf17

Processing Batch 10 (Rows 1017495 to 1120290)

 [Sun, 15 Mar 2026 21:04:56] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000015.root for sample jf17
 [Sun, 15 Mar 2026 21:04:57] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000027.root for sample jf17
 [Sun, 15 Mar 2026 21:04:57] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000016.root for sample jf17
 [Sun, 15 Mar 2026 21:04:57] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000014.root for sample jf17
 [Sun, 15 Mar 2026 21:04:57] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000037.root for sample jf17
 [Sun, 15 Mar 2026 21:04:58] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000043.root for sample jf17
 [Sun, 15 Mar 2026 21:04:58] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000018.root for sample jf17
 [Sun, 15 Mar 2026 21:04:58] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000051.root for sample jf17
 [Sun, 15 Mar 2026 21:04:59] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000021.root for sample jf17
 [Sun, 15 Mar 2026 21:04:59] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000017.root for sample jf17

Processing Batch 11 (Rows 1120290 to 1223219)

 [Sun, 15 Mar 2026 21:05:00] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000035.root for sample jf17
 [Sun, 15 Mar 2026 21:05:00] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000012.root for sample jf17
 [Sun, 15 Mar 2026 21:05:01] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000026.root for sample jf17
 [Sun, 15 Mar 2026 21:05:01] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000053.root for sample jf17
 [Sun, 15 Mar 2026 21:05:01] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000044.root for sample jf17
 [Sun, 15 Mar 2026 21:05:01] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000030.root for sample jf17
 [Sun, 15 Mar 2026 21:05:02] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000033.root for sample jf17
 [Sun, 15 Mar 2026 21:05:02] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000056.root for sample jf17
 [Sun, 15 Mar 2026 21:05:02] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000050.root for sample jf17
 [Sun, 15 Mar 2026 21:05:03] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000042.root for sample jf17

Processing Batch 12 (Rows 1223219 to 1324551)

 [Sun, 15 Mar 2026 21:05:04] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000013.root for sample jf17
 [Sun, 15 Mar 2026 21:05:04] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000025.root for sample jf17
 [Sun, 15 Mar 2026 21:05:04] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000046.root for sample jf17
 [Sun, 15 Mar 2026 21:05:05] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000032.root for sample jf17
 [Sun, 15 Mar 2026 21:05:05] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000040.root for sample jf17
 [Sun, 15 Mar 2026 21:05:05] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000045.root for sample jf17
 [Sun, 15 Mar 2026 21:05:06] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000011.root for sample jf17
 [Sun, 15 Mar 2026 21:05:06] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000031.root for sample jf17
 [Sun, 15 Mar 2026 21:05:06] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000023.root for sample jf17
 [Sun, 15 Mar 2026 21:05:06] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000054.root for sample jf17

Processing Batch 13 (Rows 1324551 to 1426159)

 [Sun, 15 Mar 2026 21:05:08] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000059.root for sample jf17
 [Sun, 15 Mar 2026 21:05:08] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000060.root for sample jf17
 [Sun, 15 Mar 2026 21:05:08] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000028.root for sample jf17
 [Sun, 15 Mar 2026 21:05:09] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000036.root for sample jf17
 [Sun, 15 Mar 2026 21:05:09] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000034.root for sample jf17
 [Sun, 15 Mar 2026 21:05:09] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000058.root for sample jf17
 [Sun, 15 Mar 2026 21:05:09] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000048.root for sample jf17
 [Sun, 15 Mar 2026 21:05:10] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000052.root for sample jf17
 [Sun, 15 Mar 2026 21:05:10] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000024.root for sample jf17
 [Sun, 15 Mar 2026 21:05:10] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000022.root for sample jf17

Processing Batch 14 (Rows 1426159 to 1528418)

 [Sun, 15 Mar 2026 21:05:12] INFO Reading /tmp/tmpq7a4wxwt/output.35439386._000039.root for sample jf17
 [Sun, 15 Mar 2026 21:05:12] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000013.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:05:14] INFO Reading /tmp/tmp7o46onao/output.35439386._000076.root for sample jf17
 [Sun, 15 Mar 2026 21:05:14] INFO Reading /tmp/tmp7o46onao/output.35439386._000100.root for sample jf17
 [Sun, 15 Mar 2026 21:05:14] INFO Reading /tmp/tmp7o46onao/output.35439386._000105.root for sample jf17
 [Sun, 15 Mar 2026 21:05:14] INFO Reading /tmp/tmp7o46onao/output.35439386._000088.root for sample jf17
 [Sun, 15 Mar 2026 21:05:15] INFO Reading /tmp/tmp7o46onao/output.35439386._000106.root for sample jf17
 [Sun, 15 Mar 2026 21:05:15] INFO Reading /tmp/tmp7o46onao/output.35439386._000089.root for sample jf17
 [Sun, 15 Mar 2026 21:05:15] INFO Reading /tmp/tmp7o46onao/output.35439386._000091.root for sample jf17
 [Sun, 15 Mar 2026 21:05:16] INFO Reading /tmp/tmp7o46onao/output.35439386._000103.root for sample jf17
 [Sun, 15 Mar 2026 21:05:16] INFO Reading /tmp/tmp7o46onao/output.35439386._000110.root for sample jf17

Processing Batch 15 (Rows 1528418 to 1630193)

 [Sun, 15 Mar 2026 21:05:17] INFO Reading /tmp/tmp7o46onao/output.35439386._000102.root for sample jf17
 [Sun, 15 Mar 2026 21:05:17] INFO Reading /tmp/tmp7o46onao/output.35439386._000098.root for sample jf17
 [Sun, 15 Mar 2026 21:05:18] INFO Reading /tmp/tmp7o46onao/output.35439386._000097.root for sample jf17
 [Sun, 15 Mar 2026 21:05:18] INFO Reading /tmp/tmp7o46onao/output.35439386._000083.root for sample jf17
 [Sun, 15 Mar 2026 21:05:18] INFO Reading /tmp/tmp7o46onao/output.35439386._000108.root for sample jf17
 [Sun, 15 Mar 2026 21:05:19] INFO Reading /tmp/tmp7o46onao/output.35439386._000109.root for sample jf17
 [Sun, 15 Mar 2026 21:05:19] INFO Reading /tmp/tmp7o46onao/output.35439386._000074.root for sample jf17
 [Sun, 15 Mar 2026 21:05:19] INFO Reading /tmp/tmp7o46onao/output.35439386._000062.root for sample jf17
 [Sun, 15 Mar 2026 21:05:20] INFO Reading /tmp/tmp7o46onao/output.35439386._000085.root for sample jf17
 [Sun, 15 Mar 2026 21:05:20] INFO Reading /tmp/tmp7o46onao/output.35439386._000107.root for sample jf17

Processing Batch 16 (Rows 1630193 to 1731999)

 [Sun, 15 Mar 2026 21:05:21] INFO Reading /tmp/tmp7o46onao/output.35439386._000063.root for sample jf17
 [Sun, 15 Mar 2026 21:05:21] INFO Reading /tmp/tmp7o46onao/output.35439386._000096.root for sample jf17
 [Sun, 15 Mar 2026 21:05:22] INFO Reading /tmp/tmp7o46onao/output.35439386._000092.root for sample jf17
 [Sun, 15 Mar 2026 21:05:22] INFO Reading /tmp/tmp7o46onao/output.35439386._000095.root for sample jf17
 [Sun, 15 Mar 2026 21:05:22] INFO Reading /tmp/tmp7o46onao/output.35439386._000087.root for sample jf17
 [Sun, 15 Mar 2026 21:05:22] INFO Reading /tmp/tmp7o46onao/output.35439386._000070.root for sample jf17
 [Sun, 15 Mar 2026 21:05:23] INFO Reading /tmp/tmp7o46onao/output.35439386._000078.root for sample jf17
 [Sun, 15 Mar 2026 21:05:23] INFO Reading /tmp/tmp7o46onao/output.35439386._000090.root for sample jf17
 [Sun, 15 Mar 2026 21:05:23] INFO Reading /tmp/tmp7o46onao/output.35439386._000094.root for sample jf17
 [Sun, 15 Mar 2026 21:05:24] INFO Reading /tmp/tmp7o46onao/output.35439386._000077.root for sample jf17

Processing Batch 17 (Rows 1731999 to 1834100)

 [Sun, 15 Mar 2026 21:05:25] INFO Reading /tmp/tmp7o46onao/output.35439386._000079.root for sample jf17
 [Sun, 15 Mar 2026 21:05:25] INFO Reading /tmp/tmp7o46onao/output.35439386._000071.root for sample jf17
 [Sun, 15 Mar 2026 21:05:25] INFO Reading /tmp/tmp7o46onao/output.35439386._000101.root for sample jf17
 [Sun, 15 Mar 2026 21:05:26] INFO Reading /tmp/tmp7o46onao/output.35439386._000086.root for sample jf17
 [Sun, 15 Mar 2026 21:05:26] INFO Reading /tmp/tmp7o46onao/output.35439386._000075.root for sample jf17
 [Sun, 15 Mar 2026 21:05:26] INFO Reading /tmp/tmp7o46onao/output.35439386._000064.root for sample jf17
 [Sun, 15 Mar 2026 21:05:27] INFO Reading /tmp/tmp7o46onao/output.35439386._000072.root for sample jf17
 [Sun, 15 Mar 2026 21:05:27] INFO Reading /tmp/tmp7o46onao/output.35439386._000067.root for sample jf17
 [Sun, 15 Mar 2026 21:05:27] INFO Reading /tmp/tmp7o46onao/output.35439386._000093.root for sample jf17
 [Sun, 15 Mar 2026 21:05:27] INFO Reading /tmp/tmp7o46onao/output.35439386._000069.root for sample jf17

Processing Batch 18 (Rows 1834100 to 1935530)

 [Sun, 15 Mar 2026 21:05:29] INFO Reading /tmp/tmp7o46onao/output.35439386._000082.root for sample jf17
 [Sun, 15 Mar 2026 21:05:29] INFO Reading /tmp/tmp7o46onao/output.35439386._000073.root for sample jf17
 [Sun, 15 Mar 2026 21:05:29] INFO Reading /tmp/tmp7o46onao/output.35439386._000099.root for sample jf17
 [Sun, 15 Mar 2026 21:05:30] INFO Reading /tmp/tmp7o46onao/output.35439386._000065.root for sample jf17
 [Sun, 15 Mar 2026 21:05:30] INFO Reading /tmp/tmp7o46onao/output.35439386._000061.root for sample jf17
 [Sun, 15 Mar 2026 21:05:30] INFO Reading /tmp/tmp7o46onao/output.35439386._000066.root for sample jf17
 [Sun, 15 Mar 2026 21:05:30] INFO Reading /tmp/tmp7o46onao/output.35439386._000081.root for sample jf17
 [Sun, 15 Mar 2026 21:05:31] INFO Reading /tmp/tmp7o46onao/output.35439386._000080.root for sample jf17
 [Sun, 15 Mar 2026 21:05:31] INFO Reading /tmp/tmp7o46onao/output.35439386._000068.root for sample jf17
 [Sun, 15 Mar 2026 21:05:31] INFO Reading /tmp/tmp7o46onao/output.35439386._000104.root for sample jf17

Processing Batch 19 (Rows 1935530 to 2037252)

 [Sun, 15 Mar 2026 21:05:32] INFO Reading /tmp/tmp7o46onao/output.35439386._000084.root for sample jf17
 [Sun, 15 Mar 2026 21:05:33] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000014.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:05:34] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000131.root for sample jf17
 [Sun, 15 Mar 2026 21:05:35] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000124.root for sample jf17
 [Sun, 15 Mar 2026 21:05:35] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000119.root for sample jf17
 [Sun, 15 Mar 2026 21:05:35] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000127.root for sample jf17
 [Sun, 15 Mar 2026 21:05:35] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000139.root for sample jf17
 [Sun, 15 Mar 2026 21:05:36] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000130.root for sample jf17
 [Sun, 15 Mar 2026 21:05:36] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000113.root for sample jf17
 [Sun, 15 Mar 2026 21:05:36] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000114.root for sample jf17
 [Sun, 15 Mar 2026 21:05:37] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000133.root for sample jf17

Processing Batch 20 (Rows 2037252 to 2139415)

 [Sun, 15 Mar 2026 21:05:38] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000123.root for sample jf17
 [Sun, 15 Mar 2026 21:05:38] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000122.root for sample jf17
 [Sun, 15 Mar 2026 21:05:38] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000125.root for sample jf17
 [Sun, 15 Mar 2026 21:05:39] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000120.root for sample jf17
 [Sun, 15 Mar 2026 21:05:39] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000136.root for sample jf17
 [Sun, 15 Mar 2026 21:05:39] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000121.root for sample jf17
 [Sun, 15 Mar 2026 21:05:40] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000116.root for sample jf17
 [Sun, 15 Mar 2026 21:05:40] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000137.root for sample jf17
 [Sun, 15 Mar 2026 21:05:40] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000111.root for sample jf17
 [Sun, 15 Mar 2026 21:05:40] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000132.root for sample jf17

Processing Batch 21 (Rows 2139415 to 2241026)

 [Sun, 15 Mar 2026 21:05:42] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000115.root for sample jf17
 [Sun, 15 Mar 2026 21:05:42] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000134.root for sample jf17
 [Sun, 15 Mar 2026 21:05:42] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000117.root for sample jf17
 [Sun, 15 Mar 2026 21:05:43] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000138.root for sample jf17
 [Sun, 15 Mar 2026 21:05:43] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000126.root for sample jf17
 [Sun, 15 Mar 2026 21:05:43] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000128.root for sample jf17
 [Sun, 15 Mar 2026 21:05:43] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000118.root for sample jf17
 [Sun, 15 Mar 2026 21:05:44] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000112.root for sample jf17
 [Sun, 15 Mar 2026 21:05:44] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000129.root for sample jf17
 [Sun, 15 Mar 2026 21:05:44] INFO Reading /tmp/tmpbeib6gf4/output.35439386._000135.root for sample jf17

Processing Batch 22 (Rows 2241026 to 2343068)

 [Sun, 15 Mar 2026 21:05:45] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000015.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:05:47] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000201.root for sample jf17
 [Sun, 15 Mar 2026 21:05:48] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000160.root for sample jf17
 [Sun, 15 Mar 2026 21:05:48] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000196.root for sample jf17
 [Sun, 15 Mar 2026 21:05:48] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000199.root for sample jf17
 [Sun, 15 Mar 2026 21:05:48] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000192.root for sample jf17
 [Sun, 15 Mar 2026 21:05:49] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000181.root for sample jf17
 [Sun, 15 Mar 2026 21:05:49] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000172.root for sample jf17
 [Sun, 15 Mar 2026 21:05:49] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000200.root for sample jf17
 [Sun, 15 Mar 2026 21:05:50] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000171.root for sample jf17
 [Sun, 15 Mar 2026 21:05:50] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000166.root for sample jf17

Processing Batch 23 (Rows 2343068 to 2444156)

 [Sun, 15 Mar 2026 21:05:51] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000189.root for sample jf17
 [Sun, 15 Mar 2026 21:05:51] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000182.root for sample jf17
 [Sun, 15 Mar 2026 21:05:52] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000190.root for sample jf17
 [Sun, 15 Mar 2026 21:05:52] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000174.root for sample jf17
 [Sun, 15 Mar 2026 21:05:52] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000191.root for sample jf17
 [Sun, 15 Mar 2026 21:05:52] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000157.root for sample jf17
 [Sun, 15 Mar 2026 21:05:53] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000161.root for sample jf17
 [Sun, 15 Mar 2026 21:05:53] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000184.root for sample jf17
 [Sun, 15 Mar 2026 21:05:53] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000162.root for sample jf17
 [Sun, 15 Mar 2026 21:05:54] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000176.root for sample jf17

Processing Batch 24 (Rows 2444156 to 2545874)

 [Sun, 15 Mar 2026 21:05:55] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000178.root for sample jf17
 [Sun, 15 Mar 2026 21:05:55] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000158.root for sample jf17
 [Sun, 15 Mar 2026 21:05:55] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000187.root for sample jf17
 [Sun, 15 Mar 2026 21:05:56] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000185.root for sample jf17
 [Sun, 15 Mar 2026 21:05:56] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000180.root for sample jf17
 [Sun, 15 Mar 2026 21:05:56] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000163.root for sample jf17
 [Sun, 15 Mar 2026 21:05:57] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000194.root for sample jf17
 [Sun, 15 Mar 2026 21:05:57] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000186.root for sample jf17
 [Sun, 15 Mar 2026 21:05:57] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000197.root for sample jf17
 [Sun, 15 Mar 2026 21:05:57] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000183.root for sample jf17

Processing Batch 25 (Rows 2545874 to 2647235)

 [Sun, 15 Mar 2026 21:05:59] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000177.root for sample jf17
 [Sun, 15 Mar 2026 21:05:59] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000175.root for sample jf17
 [Sun, 15 Mar 2026 21:05:59] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000173.root for sample jf17
 [Sun, 15 Mar 2026 21:05:59] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000164.root for sample jf17
 [Sun, 15 Mar 2026 21:06:00] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000203.root for sample jf17
 [Sun, 15 Mar 2026 21:06:00] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000155.root for sample jf17
 [Sun, 15 Mar 2026 21:06:00] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000168.root for sample jf17
 [Sun, 15 Mar 2026 21:06:01] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000159.root for sample jf17
 [Sun, 15 Mar 2026 21:06:01] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000169.root for sample jf17
 [Sun, 15 Mar 2026 21:06:01] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000202.root for sample jf17

Processing Batch 26 (Rows 2647235 to 2748095)

 [Sun, 15 Mar 2026 21:06:02] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000204.root for sample jf17
 [Sun, 15 Mar 2026 21:06:03] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000167.root for sample jf17
 [Sun, 15 Mar 2026 21:06:03] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000170.root for sample jf17
 [Sun, 15 Mar 2026 21:06:03] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000198.root for sample jf17
 [Sun, 15 Mar 2026 21:06:04] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000179.root for sample jf17
 [Sun, 15 Mar 2026 21:06:04] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000193.root for sample jf17
 [Sun, 15 Mar 2026 21:06:04] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000165.root for sample jf17
 [Sun, 15 Mar 2026 21:06:04] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000156.root for sample jf17
 [Sun, 15 Mar 2026 21:06:05] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000195.root for sample jf17
 [Sun, 15 Mar 2026 21:06:05] INFO Reading /tmp/tmpc2hy1_ni/output.35439386._000188.root for sample jf17

Processing Batch 27 (Rows 2748095 to 2850135)

 [Sun, 15 Mar 2026 21:06:06] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000016.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:06:08] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000234.root for sample jf17
 [Sun, 15 Mar 2026 21:06:08] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000217.root for sample jf17
 [Sun, 15 Mar 2026 21:06:09] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000231.root for sample jf17
 [Sun, 15 Mar 2026 21:06:09] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000228.root for sample jf17
 [Sun, 15 Mar 2026 21:06:09] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000212.root for sample jf17
 [Sun, 15 Mar 2026 21:06:09] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000226.root for sample jf17
 [Sun, 15 Mar 2026 21:06:10] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000233.root for sample jf17
 [Sun, 15 Mar 2026 21:06:10] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000249.root for sample jf17
 [Sun, 15 Mar 2026 21:06:10] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000252.root for sample jf17
 [Sun, 15 Mar 2026 21:06:11] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000213.root for sample jf17

Processing Batch 28 (Rows 2850135 to 2952027)

 [Sun, 15 Mar 2026 21:06:12] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000244.root for sample jf17
 [Sun, 15 Mar 2026 21:06:12] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000243.root for sample jf17
 [Sun, 15 Mar 2026 21:06:12] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000221.root for sample jf17
 [Sun, 15 Mar 2026 21:06:13] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000223.root for sample jf17
 [Sun, 15 Mar 2026 21:06:13] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000219.root for sample jf17
 [Sun, 15 Mar 2026 21:06:13] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000227.root for sample jf17
 [Sun, 15 Mar 2026 21:06:14] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000209.root for sample jf17
 [Sun, 15 Mar 2026 21:06:14] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000251.root for sample jf17
 [Sun, 15 Mar 2026 21:06:14] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000216.root for sample jf17
 [Sun, 15 Mar 2026 21:06:14] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000224.root for sample jf17

Processing Batch 29 (Rows 2952027 to 3053660)

 [Sun, 15 Mar 2026 21:06:16] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000220.root for sample jf17
 [Sun, 15 Mar 2026 21:06:16] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000238.root for sample jf17
 [Sun, 15 Mar 2026 21:06:16] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000229.root for sample jf17
 [Sun, 15 Mar 2026 21:06:17] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000235.root for sample jf17
 [Sun, 15 Mar 2026 21:06:17] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000225.root for sample jf17
 [Sun, 15 Mar 2026 21:06:17] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000236.root for sample jf17
 [Sun, 15 Mar 2026 21:06:17] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000250.root for sample jf17
 [Sun, 15 Mar 2026 21:06:18] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000208.root for sample jf17
 [Sun, 15 Mar 2026 21:06:18] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000230.root for sample jf17
 [Sun, 15 Mar 2026 21:06:18] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000237.root for sample jf17

Processing Batch 30 (Rows 3053660 to 3154690)

 [Sun, 15 Mar 2026 21:06:20] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000207.root for sample jf17
 [Sun, 15 Mar 2026 21:06:20] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000246.root for sample jf17
 [Sun, 15 Mar 2026 21:06:20] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000206.root for sample jf17
 [Sun, 15 Mar 2026 21:06:21] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000215.root for sample jf17
 [Sun, 15 Mar 2026 21:06:21] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000239.root for sample jf17
 [Sun, 15 Mar 2026 21:06:21] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000248.root for sample jf17
 [Sun, 15 Mar 2026 21:06:21] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000245.root for sample jf17
 [Sun, 15 Mar 2026 21:06:22] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000247.root for sample jf17
 [Sun, 15 Mar 2026 21:06:22] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000210.root for sample jf17
 [Sun, 15 Mar 2026 21:06:22] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000211.root for sample jf17

Processing Batch 31 (Rows 3154690 to 3256735)

 [Sun, 15 Mar 2026 21:06:23] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000232.root for sample jf17
 [Sun, 15 Mar 2026 21:06:24] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000205.root for sample jf17
 [Sun, 15 Mar 2026 21:06:24] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000240.root for sample jf17
 [Sun, 15 Mar 2026 21:06:24] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000218.root for sample jf17
 [Sun, 15 Mar 2026 21:06:25] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000242.root for sample jf17
 [Sun, 15 Mar 2026 21:06:25] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000222.root for sample jf17
 [Sun, 15 Mar 2026 21:06:25] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000214.root for sample jf17
 [Sun, 15 Mar 2026 21:06:26] INFO Reading /tmp/tmpd1d9kbjy/output.35439386._000241.root for sample jf17
 [Sun, 15 Mar 2026 21:06:26] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000017.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:06:28] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000303.root for sample jf17
 [Sun, 15 Mar 2026 21:06:28] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000319.root for sample jf17

Processing Batch 32 (Rows 3256735 to 3358567)

 [Sun, 15 Mar 2026 21:06:29] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000269.root for sample jf17
 [Sun, 15 Mar 2026 21:06:29] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000320.root for sample jf17
 [Sun, 15 Mar 2026 21:06:30] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000263.root for sample jf17
 [Sun, 15 Mar 2026 21:06:30] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000259.root for sample jf17
 [Sun, 15 Mar 2026 21:06:30] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000258.root for sample jf17
 [Sun, 15 Mar 2026 21:06:31] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000309.root for sample jf17
 [Sun, 15 Mar 2026 21:06:31] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000325.root for sample jf17
 [Sun, 15 Mar 2026 21:06:31] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000274.root for sample jf17
 [Sun, 15 Mar 2026 21:06:31] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000317.root for sample jf17
 [Sun, 15 Mar 2026 21:06:32] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000253.root for sample jf17

Processing Batch 33 (Rows 3358567 to 3460549)

 [Sun, 15 Mar 2026 21:06:33] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000260.root for sample jf17
 [Sun, 15 Mar 2026 21:06:33] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000327.root for sample jf17
 [Sun, 15 Mar 2026 21:06:34] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000305.root for sample jf17
 [Sun, 15 Mar 2026 21:06:34] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000311.root for sample jf17
 [Sun, 15 Mar 2026 21:06:34] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000304.root for sample jf17
 [Sun, 15 Mar 2026 21:06:35] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000314.root for sample jf17
 [Sun, 15 Mar 2026 21:06:35] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000308.root for sample jf17
 [Sun, 15 Mar 2026 21:06:35] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000316.root for sample jf17
 [Sun, 15 Mar 2026 21:06:35] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000265.root for sample jf17
 [Sun, 15 Mar 2026 21:06:36] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000307.root for sample jf17

Processing Batch 34 (Rows 3460549 to 3562431)

 [Sun, 15 Mar 2026 21:06:37] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000267.root for sample jf17
 [Sun, 15 Mar 2026 21:06:37] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000257.root for sample jf17
 [Sun, 15 Mar 2026 21:06:37] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000256.root for sample jf17
 [Sun, 15 Mar 2026 21:06:38] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000266.root for sample jf17
 [Sun, 15 Mar 2026 21:06:38] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000261.root for sample jf17
 [Sun, 15 Mar 2026 21:06:38] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000322.root for sample jf17
 [Sun, 15 Mar 2026 21:06:39] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000318.root for sample jf17
 [Sun, 15 Mar 2026 21:06:39] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000275.root for sample jf17
 [Sun, 15 Mar 2026 21:06:39] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000321.root for sample jf17
 [Sun, 15 Mar 2026 21:06:40] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000324.root for sample jf17

Processing Batch 35 (Rows 3562431 to 3663771)

 [Sun, 15 Mar 2026 21:06:41] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000254.root for sample jf17
 [Sun, 15 Mar 2026 21:06:41] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000310.root for sample jf17
 [Sun, 15 Mar 2026 21:06:41] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000273.root for sample jf17
 [Sun, 15 Mar 2026 21:06:42] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000270.root for sample jf17
 [Sun, 15 Mar 2026 21:06:42] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000277.root for sample jf17
 [Sun, 15 Mar 2026 21:06:42] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000306.root for sample jf17
 [Sun, 15 Mar 2026 21:06:42] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000271.root for sample jf17
 [Sun, 15 Mar 2026 21:06:43] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000312.root for sample jf17
 [Sun, 15 Mar 2026 21:06:43] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000313.root for sample jf17
 [Sun, 15 Mar 2026 21:06:43] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000262.root for sample jf17

Processing Batch 36 (Rows 3663771 to 3766149)

 [Sun, 15 Mar 2026 21:06:45] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000326.root for sample jf17
 [Sun, 15 Mar 2026 21:06:45] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000264.root for sample jf17
 [Sun, 15 Mar 2026 21:06:45] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000272.root for sample jf17
 [Sun, 15 Mar 2026 21:06:45] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000255.root for sample jf17
 [Sun, 15 Mar 2026 21:06:46] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000276.root for sample jf17
 [Sun, 15 Mar 2026 21:06:46] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000323.root for sample jf17
 [Sun, 15 Mar 2026 21:06:46] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000315.root for sample jf17
 [Sun, 15 Mar 2026 21:06:47] INFO Reading /tmp/tmpc7m4q45w/output.35439386._000268.root for sample jf17
 [Sun, 15 Mar 2026 21:06:47] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000018.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:06:49] INFO Reading /tmp/tmp6q421vs9/output.35439386._000377.root for sample jf17
 [Sun, 15 Mar 2026 21:06:49] INFO Reading /tmp/tmp6q421vs9/output.35439386._000406.root for sample jf17

Processing Batch 37 (Rows 3766149 to 3868599)

 [Sun, 15 Mar 2026 21:06:50] INFO Reading /tmp/tmp6q421vs9/output.35439386._000376.root for sample jf17
 [Sun, 15 Mar 2026 21:06:50] INFO Reading /tmp/tmp6q421vs9/output.35439386._000400.root for sample jf17
 [Sun, 15 Mar 2026 21:06:51] INFO Reading /tmp/tmp6q421vs9/output.35439386._000399.root for sample jf17
 [Sun, 15 Mar 2026 21:06:51] INFO Reading /tmp/tmp6q421vs9/output.35439386._000370.root for sample jf17
 [Sun, 15 Mar 2026 21:06:51] INFO Reading /tmp/tmp6q421vs9/output.35439386._000391.root for sample jf17
 [Sun, 15 Mar 2026 21:06:52] INFO Reading /tmp/tmp6q421vs9/output.35439386._000384.root for sample jf17
 [Sun, 15 Mar 2026 21:06:52] INFO Reading /tmp/tmp6q421vs9/output.35439386._000383.root for sample jf17
 [Sun, 15 Mar 2026 21:06:52] INFO Reading /tmp/tmp6q421vs9/output.35439386._000396.root for sample jf17
 [Sun, 15 Mar 2026 21:06:52] INFO Reading /tmp/tmp6q421vs9/output.35439386._000389.root for sample jf17
 [Sun, 15 Mar 2026 21:06:53] INFO Reading /tmp/tmp6q421vs9/output.35439386._000367.root for sample jf17

Processing Batch 38 (Rows 3868599 to 3969604)

 [Sun, 15 Mar 2026 21:06:54] INFO Reading /tmp/tmp6q421vs9/output.35439386._000373.root for sample jf17
 [Sun, 15 Mar 2026 21:06:54] INFO Reading /tmp/tmp6q421vs9/output.35439386._000374.root for sample jf17
 [Sun, 15 Mar 2026 21:06:55] INFO Reading /tmp/tmp6q421vs9/output.35439386._000414.root for sample jf17
 [Sun, 15 Mar 2026 21:06:55] INFO Reading /tmp/tmp6q421vs9/output.35439386._000403.root for sample jf17
 [Sun, 15 Mar 2026 21:06:55] INFO Reading /tmp/tmp6q421vs9/output.35439386._000385.root for sample jf17
 [Sun, 15 Mar 2026 21:06:56] INFO Reading /tmp/tmp6q421vs9/output.35439386._000368.root for sample jf17
 [Sun, 15 Mar 2026 21:06:56] INFO Reading /tmp/tmp6q421vs9/output.35439386._000394.root for sample jf17
 [Sun, 15 Mar 2026 21:06:56] INFO Reading /tmp/tmp6q421vs9/output.35439386._000407.root for sample jf17
 [Sun, 15 Mar 2026 21:06:56] INFO Reading /tmp/tmp6q421vs9/output.35439386._000409.root for sample jf17
 [Sun, 15 Mar 2026 21:06:57] INFO Reading /tmp/tmp6q421vs9/output.35439386._000386.root for sample jf17

Processing Batch 39 (Rows 3969604 to 4071290)

 [Sun, 15 Mar 2026 21:06:58] INFO Reading /tmp/tmp6q421vs9/output.35439386._000387.root for sample jf17
 [Sun, 15 Mar 2026 21:06:58] INFO Reading /tmp/tmp6q421vs9/output.35439386._000392.root for sample jf17
 [Sun, 15 Mar 2026 21:06:58] INFO Reading /tmp/tmp6q421vs9/output.35439386._000404.root for sample jf17
 [Sun, 15 Mar 2026 21:06:59] INFO Reading /tmp/tmp6q421vs9/output.35439386._000402.root for sample jf17
 [Sun, 15 Mar 2026 21:06:59] INFO Reading /tmp/tmp6q421vs9/output.35439386._000382.root for sample jf17
 [Sun, 15 Mar 2026 21:06:59] INFO Reading /tmp/tmp6q421vs9/output.35439386._000388.root for sample jf17
 [Sun, 15 Mar 2026 21:07:00] INFO Reading /tmp/tmp6q421vs9/output.35439386._000378.root for sample jf17
 [Sun, 15 Mar 2026 21:07:00] INFO Reading /tmp/tmp6q421vs9/output.35439386._000401.root for sample jf17
 [Sun, 15 Mar 2026 21:07:00] INFO Reading /tmp/tmp6q421vs9/output.35439386._000366.root for sample jf17
 [Sun, 15 Mar 2026 21:07:00] INFO Reading /tmp/tmp6q421vs9/output.35439386._000372.root for sample jf17

Processing Batch 40 (Rows 4071290 to 4173186)

 [Sun, 15 Mar 2026 21:07:02] INFO Reading /tmp/tmp6q421vs9/output.35439386._000371.root for sample jf17
 [Sun, 15 Mar 2026 21:07:02] INFO Reading /tmp/tmp6q421vs9/output.35439386._000410.root for sample jf17
 [Sun, 15 Mar 2026 21:07:02] INFO Reading /tmp/tmp6q421vs9/output.35439386._000412.root for sample jf17
 [Sun, 15 Mar 2026 21:07:03] INFO Reading /tmp/tmp6q421vs9/output.35439386._000393.root for sample jf17
 [Sun, 15 Mar 2026 21:07:03] INFO Reading /tmp/tmp6q421vs9/output.35439386._000411.root for sample jf17
 [Sun, 15 Mar 2026 21:07:03] INFO Reading /tmp/tmp6q421vs9/output.35439386._000413.root for sample jf17
 [Sun, 15 Mar 2026 21:07:03] INFO Reading /tmp/tmp6q421vs9/output.35439386._000380.root for sample jf17
 [Sun, 15 Mar 2026 21:07:04] INFO Reading /tmp/tmp6q421vs9/output.35439386._000375.root for sample jf17
 [Sun, 15 Mar 2026 21:07:04] INFO Reading /tmp/tmp6q421vs9/output.35439386._000405.root for sample jf17
 [Sun, 15 Mar 2026 21:07:04] INFO Reading /tmp/tmp6q421vs9/output.35439386._000397.root for sample jf17

Processing Batch 41 (Rows 4173186 to 4275030)

 [Sun, 15 Mar 2026 21:07:05] INFO Reading /tmp/tmp6q421vs9/output.35439386._000390.root for sample jf17
 [Sun, 15 Mar 2026 21:07:06] INFO Reading /tmp/tmp6q421vs9/output.35439386._000408.root for sample jf17
 [Sun, 15 Mar 2026 21:07:06] INFO Reading /tmp/tmp6q421vs9/output.35439386._000379.root for sample jf17
 [Sun, 15 Mar 2026 21:07:06] INFO Reading /tmp/tmp6q421vs9/output.35439386._000381.root for sample jf17
 [Sun, 15 Mar 2026 21:07:07] INFO Reading /tmp/tmp6q421vs9/output.35439386._000395.root for sample jf17
 [Sun, 15 Mar 2026 21:07:07] INFO Reading /tmp/tmp6q421vs9/output.35439386._000365.root for sample jf17
 [Sun, 15 Mar 2026 21:07:07] INFO Reading /tmp/tmp6q421vs9/output.35439386._000369.root for sample jf17
 [Sun, 15 Mar 2026 21:07:08] INFO Reading /tmp/tmp6q421vs9/output.35439386._000398.root for sample jf17
 [Sun, 15 Mar 2026 21:07:08] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000019.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:09] INFO Reading /tmp/tmp1e_50yay/output.35439386._000433.root for sample jf17
 [Sun, 15 Mar 2026 21:07:09] INFO Reading /tmp/tmp1e_50yay/output.35439386._000430.root for sample jf17

Processing Batch 42 (Rows 4275030 to 4376705)

 [Sun, 15 Mar 2026 21:07:11] INFO Reading /tmp/tmp1e_50yay/output.35439386._000429.root for sample jf17
 [Sun, 15 Mar 2026 21:07:11] INFO Reading /tmp/tmp1e_50yay/output.35439386._000417.root for sample jf17
 [Sun, 15 Mar 2026 21:07:11] INFO Reading /tmp/tmp1e_50yay/output.35439386._000432.root for sample jf17
 [Sun, 15 Mar 2026 21:07:12] INFO Reading /tmp/tmp1e_50yay/output.35439386._000446.root for sample jf17
 [Sun, 15 Mar 2026 21:07:12] INFO Reading /tmp/tmp1e_50yay/output.35439386._000428.root for sample jf17
 [Sun, 15 Mar 2026 21:07:12] INFO Reading /tmp/tmp1e_50yay/output.35439386._000422.root for sample jf17
 [Sun, 15 Mar 2026 21:07:12] INFO Reading /tmp/tmp1e_50yay/output.35439386._000420.root for sample jf17
 [Sun, 15 Mar 2026 21:07:13] INFO Reading /tmp/tmp1e_50yay/output.35439386._000436.root for sample jf17
 [Sun, 15 Mar 2026 21:07:13] INFO Reading /tmp/tmp1e_50yay/output.35439386._000444.root for sample jf17
 [Sun, 15 Mar 2026 21:07:13] INFO Reading /tmp/tmp1e_50yay/output.35439386._000442.root for sample jf17

Processing Batch 43 (Rows 4376705 to 4478855)

 [Sun, 15 Mar 2026 21:07:15] INFO Reading /tmp/tmp1e_50yay/output.35439386._000437.root for sample jf17
 [Sun, 15 Mar 2026 21:07:15] INFO Reading /tmp/tmp1e_50yay/output.35439386._000439.root for sample jf17
 [Sun, 15 Mar 2026 21:07:15] INFO Reading /tmp/tmp1e_50yay/output.35439386._000418.root for sample jf17
 [Sun, 15 Mar 2026 21:07:15] INFO Reading /tmp/tmp1e_50yay/output.35439386._000421.root for sample jf17
 [Sun, 15 Mar 2026 21:07:16] INFO Reading /tmp/tmp1e_50yay/output.35439386._000431.root for sample jf17
 [Sun, 15 Mar 2026 21:07:16] INFO Reading /tmp/tmp1e_50yay/output.35439386._000425.root for sample jf17
 [Sun, 15 Mar 2026 21:07:16] INFO Reading /tmp/tmp1e_50yay/output.35439386._000424.root for sample jf17
 [Sun, 15 Mar 2026 21:07:17] INFO Reading /tmp/tmp1e_50yay/output.35439386._000443.root for sample jf17
 [Sun, 15 Mar 2026 21:07:17] INFO Reading /tmp/tmp1e_50yay/output.35439386._000435.root for sample jf17
 [Sun, 15 Mar 2026 21:07:17] INFO Reading /tmp/tmp1e_50yay/output.35439386._000438.root for sample jf17

Processing Batch 44 (Rows 4478855 to 4580565)

 [Sun, 15 Mar 2026 21:07:18] INFO Reading /tmp/tmp1e_50yay/output.35439386._000434.root for sample jf17
 [Sun, 15 Mar 2026 21:07:19] INFO Reading /tmp/tmp1e_50yay/output.35439386._000416.root for sample jf17
 [Sun, 15 Mar 2026 21:07:19] INFO Reading /tmp/tmp1e_50yay/output.35439386._000423.root for sample jf17
 [Sun, 15 Mar 2026 21:07:19] INFO Reading /tmp/tmp1e_50yay/output.35439386._000427.root for sample jf17
 [Sun, 15 Mar 2026 21:07:20] INFO Reading /tmp/tmp1e_50yay/output.35439386._000447.root for sample jf17
 [Sun, 15 Mar 2026 21:07:20] INFO Reading /tmp/tmp1e_50yay/output.35439386._000445.root for sample jf17
 [Sun, 15 Mar 2026 21:07:20] INFO Reading /tmp/tmp1e_50yay/output.35439386._000426.root for sample jf17
 [Sun, 15 Mar 2026 21:07:20] INFO Reading /tmp/tmp1e_50yay/output.35439386._000441.root for sample jf17
 [Sun, 15 Mar 2026 21:07:21] INFO Reading /tmp/tmp1e_50yay/output.35439386._000440.root for sample jf17
 [Sun, 15 Mar 2026 21:07:21] INFO Reading /tmp/tmp1e_50yay/output.35439386._000415.root for sample jf17

Processing Batch 45 (Rows 4580565 to 4682086)

 [Sun, 15 Mar 2026 21:07:22] INFO Reading /tmp/tmp1e_50yay/output.35439386._000419.root for sample jf17
 [Sun, 15 Mar 2026 21:07:23] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000020.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:23] INFO Reading /tmp/tmpqncdk9se/output.35439386._000503.root for sample jf17
 [Sun, 15 Mar 2026 21:07:23] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000021.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:24] INFO Reading /tmp/tmpelsgfbue/output.35439386._000481.root for sample jf17
 [Sun, 15 Mar 2026 21:07:24] INFO Reading /tmp/tmpelsgfbue/output.35439386._000482.root for sample jf17
 [Sun, 15 Mar 2026 21:07:24] INFO Reading /tmp/tmpelsgfbue/output.35439386._000483.root for sample jf17
 [Sun, 15 Mar 2026 21:07:25] INFO Reading /tmp/tmpelsgfbue/output.35439386._000487.root for sample jf17
 [Sun, 15 Mar 2026 21:07:25] INFO Reading /tmp/tmpelsgfbue/output.35439386._000488.root for sample jf17
 [Sun, 15 Mar 2026 21:07:25] INFO Reading /tmp/tmpelsgfbue/output.35439386._000495.root for sample jf17
 [Sun, 15 Mar 2026 21:07:26] INFO Reading /tmp/tmpelsgfbue/output.35439386._000491.root for sample jf17
 [Sun, 15 Mar 2026 21:07:26] INFO Reading /tmp/tmpelsgfbue/output.35439386._000477.root for sample jf17

Processing Batch 46 (Rows 4682086 to 4784034)

 [Sun, 15 Mar 2026 21:07:27] INFO Reading /tmp/tmpelsgfbue/output.35439386._000478.root for sample jf17
 [Sun, 15 Mar 2026 21:07:27] INFO Reading /tmp/tmpelsgfbue/output.35439386._000497.root for sample jf17
 [Sun, 15 Mar 2026 21:07:28] INFO Reading /tmp/tmpelsgfbue/output.35439386._000496.root for sample jf17
 [Sun, 15 Mar 2026 21:07:28] INFO Reading /tmp/tmpelsgfbue/output.35439386._000490.root for sample jf17
 [Sun, 15 Mar 2026 21:07:28] INFO Reading /tmp/tmpelsgfbue/output.35439386._000476.root for sample jf17
 [Sun, 15 Mar 2026 21:07:28] INFO Reading /tmp/tmpelsgfbue/output.35439386._000474.root for sample jf17
 [Sun, 15 Mar 2026 21:07:29] INFO Reading /tmp/tmpelsgfbue/output.35439386._000493.root for sample jf17
 [Sun, 15 Mar 2026 21:07:29] INFO Reading /tmp/tmpelsgfbue/output.35439386._000492.root for sample jf17
 [Sun, 15 Mar 2026 21:07:29] INFO Reading /tmp/tmpelsgfbue/output.35439386._000489.root for sample jf17
 [Sun, 15 Mar 2026 21:07:30] INFO Reading /tmp/tmpelsgfbue/output.35439386._000473.root for sample jf17

Processing Batch 47 (Rows 4784034 to 4885748)

 [Sun, 15 Mar 2026 21:07:31] INFO Reading /tmp/tmpelsgfbue/output.35439386._000494.root for sample jf17
 [Sun, 15 Mar 2026 21:07:31] INFO Reading /tmp/tmpelsgfbue/output.35439386._000486.root for sample jf17
 [Sun, 15 Mar 2026 21:07:31] INFO Reading /tmp/tmpelsgfbue/output.35439386._000480.root for sample jf17
 [Sun, 15 Mar 2026 21:07:32] INFO Reading /tmp/tmpelsgfbue/output.35439386._000475.root for sample jf17
 [Sun, 15 Mar 2026 21:07:32] INFO Reading /tmp/tmpelsgfbue/output.35439386._000484.root for sample jf17
 [Sun, 15 Mar 2026 21:07:32] INFO Reading /tmp/tmpelsgfbue/output.35439386._000485.root for sample jf17
 [Sun, 15 Mar 2026 21:07:33] INFO Reading /tmp/tmpelsgfbue/output.35439386._000479.root for sample jf17
 [Sun, 15 Mar 2026 21:07:33] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000022.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:33] INFO Reading /tmp/tmph8qsnsp7/output.35439386._000510.root for sample jf17
 [Sun, 15 Mar 2026 21:07:33] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000023.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:33] INFO Reading /tmp/tmpjbmnzy1g/output.35439386._000504.root for sample jf17
 [Sun, 15 Mar 2026 21:07:33] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000024.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:34] INFO Reading /tmp/tmphf899865/output.35439386._000509.root for sample jf17

Processing Batch 48 (Rows 4885748 to 4988047)

 [Sun, 15 Mar 2026 21:07:35] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000025.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:35] INFO Reading /tmp/tmp1i6_64ic/output.35439386._000511.root for sample jf17
 [Sun, 15 Mar 2026 21:07:35] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000026.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:35] INFO Reading /tmp/tmp3ybxbosr/output.35439386._000507.root for sample jf17
 [Sun, 15 Mar 2026 21:07:35] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000027.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:35] INFO Reading /tmp/tmp2i06s700/output.35439386._000508.root for sample jf17
 [Sun, 15 Mar 2026 21:07:36] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000028.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:36] INFO Reading /tmp/tmpy_gwcyqw/output.35439386._000501.root for sample jf17
 [Sun, 15 Mar 2026 21:07:36] INFO Reading /tmp/tmpy_gwcyqw/output.35439386._000500.root for sample jf17
 [Sun, 15 Mar 2026 21:07:36] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000029.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:36] INFO Reading /tmp/tmpn8fc3eev/output.35439386._000502.root for sample jf17
 [Sun, 15 Mar 2026 21:07:37] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000030.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:37] INFO Reading /tmp/tmp35vlio4n/output.35439386._000506.root for sample jf17
 [Sun, 15 Mar 2026 21:07:37] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/bkg/user.isilvafe.user.isilvafe.mc21_13p6TeV.JF17.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_jf17_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439386._000031.XYZ.root.tgz for sample jf17
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:37] INFO Reading /tmp/tmp9nc2659y/output.35439386._000505.root for sample jf17
 [Sun, 15 Mar 2026 21:07:37] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000001.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:37] INFO Reading /tmp/tmpvd5bb09w/output.35439375._000004.root for sample zee
 [Sun, 15 Mar 2026 21:07:37] INFO Reading /tmp/tmpvd5bb09w/output.35439375._000003.root for sample zee
 [Sun, 15 Mar 2026 21:07:38] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000002.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:38] INFO Reading /tmp/tmpvd29l86x/output.35439375._000002.root for sample zee
 [Sun, 15 Mar 2026 21:07:38] INFO Reading /tmp/tmpvd29l86x/output.35439375._000001.root for sample zee
 [Sun, 15 Mar 2026 21:07:38] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000003.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:38] INFO Reading /tmp/tmptodgxhkd/output.35439375._000006.root for sample zee

Processing Batch 49 (Rows 4988047 to 5091868)

 [Sun, 15 Mar 2026 21:07:39] INFO Reading /tmp/tmptodgxhkd/output.35439375._000007.root for sample zee
 [Sun, 15 Mar 2026 21:07:39] INFO Reading /tmp/tmptodgxhkd/output.35439375._000005.root for sample zee
 [Sun, 15 Mar 2026 21:07:40] INFO Reading /tmp/tmptodgxhkd/output.35439375._000009.root for sample zee
 [Sun, 15 Mar 2026 21:07:40] INFO Reading /tmp/tmptodgxhkd/output.35439375._000010.root for sample zee
 [Sun, 15 Mar 2026 21:07:40] INFO Reading /tmp/tmptodgxhkd/output.35439375._000008.root for sample zee
 [Sun, 15 Mar 2026 21:07:40] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000004.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:40] INFO Reading /tmp/tmpa7dz7_ve/output.35439375._000012.root for sample zee
 [Sun, 15 Mar 2026 21:07:40] INFO Reading /tmp/tmpa7dz7_ve/output.35439375._000016.root for sample zee
 [Sun, 15 Mar 2026 21:07:41] INFO Reading /tmp/tmpa7dz7_ve/output.35439375._000017.root for sample zee
 [Sun, 15 Mar 2026 21:07:41] INFO Reading /tmp/tmpa7dz7_ve/output.35439375._000015.root for sample zee
 [Sun, 15 Mar 2026 21:07:41] INFO Reading /tmp/tmpa7dz7_ve/output.35439375._000014.root for sample zee
 [Sun, 15 Mar 2026 21:07:41] INFO Reading /tmp/tmpa7dz7_ve/output.35439375._000013.root for sample zee
 [Sun, 15 Mar 2026 21:07:41] INFO Reading /tmp/tmpa7dz7_ve/output.35439375._000011.root for sample zee
 [Sun, 15 Mar 2026 21:07:41] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000005.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:42] INFO Reading /tmp/tmp512x4u5e/output.35439375._000095.root for sample zee
 [Sun, 15 Mar 2026 21:07:42] INFO Reading /tmp/tmp512x4u5e/output.35439375._000096.root for sample zee
 [Sun, 15 Mar 2026 21:07:42] INFO Reading /tmp/tmp512x4u5e/output.35439375._000094.root for sample zee
 [Sun, 15 Mar 2026 21:07:42] INFO Reading /tmp/tmp512x4u5e/output.35439375._000093.root for sample zee
 [Sun, 15 Mar 2026 21:07:42] INFO Reading /tmp/tmp512x4u5e/output.35439375._000097.root for sample zee
 [Sun, 15 Mar 2026 21:07:42] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000006.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:43] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000448.root for sample zee
 [Sun, 15 Mar 2026 21:07:43] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000442.root for sample zee
 [Sun, 15 Mar 2026 21:07:43] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000438.root for sample zee
 [Sun, 15 Mar 2026 21:07:43] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000444.root for sample zee
 [Sun, 15 Mar 2026 21:07:44] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000429.root for sample zee
 [Sun, 15 Mar 2026 21:07:44] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000430.root for sample zee

Processing Batch 50 (Rows 5091868 to 5192551)

 [Sun, 15 Mar 2026 21:07:45] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000449.root for sample zee
 [Sun, 15 Mar 2026 21:07:45] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000433.root for sample zee
 [Sun, 15 Mar 2026 21:07:45] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000425.root for sample zee
 [Sun, 15 Mar 2026 21:07:45] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000439.root for sample zee
 [Sun, 15 Mar 2026 21:07:45] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000436.root for sample zee
 [Sun, 15 Mar 2026 21:07:46] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000431.root for sample zee
 [Sun, 15 Mar 2026 21:07:46] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000441.root for sample zee
 [Sun, 15 Mar 2026 21:07:46] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000445.root for sample zee
 [Sun, 15 Mar 2026 21:07:46] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000435.root for sample zee
 [Sun, 15 Mar 2026 21:07:46] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000437.root for sample zee
 [Sun, 15 Mar 2026 21:07:46] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000443.root for sample zee
 [Sun, 15 Mar 2026 21:07:47] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000426.root for sample zee
 [Sun, 15 Mar 2026 21:07:47] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000428.root for sample zee
 [Sun, 15 Mar 2026 21:07:47] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000440.root for sample zee
 [Sun, 15 Mar 2026 21:07:47] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000447.root for sample zee
 [Sun, 15 Mar 2026 21:07:47] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000446.root for sample zee
 [Sun, 15 Mar 2026 21:07:48] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000427.root for sample zee
 [Sun, 15 Mar 2026 21:07:48] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000434.root for sample zee
 [Sun, 15 Mar 2026 21:07:48] INFO Reading /tmp/tmpbvt4hxtz/output.35439375._000432.root for sample zee
 [Sun, 15 Mar 2026 21:07:48] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000007.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:48] INFO Reading /tmp/tmp1vkrbrxt/output.35439375._000098.root for sample zee
 [Sun, 15 Mar 2026 21:07:48] INFO Reading /tmp/tmp1vkrbrxt/output.35439375._000099.root for sample zee
 [Sun, 15 Mar 2026 21:07:48] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000008.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:49] INFO Reading /tmp/tmpzyinltmc/output.35439375._000078.root for sample zee
 [Sun, 15 Mar 2026 21:07:49] INFO Reading /tmp/tmpzyinltmc/output.35439375._000084.root for sample zee

Processing Batch 51 (Rows 5192551 to 5293157)

 [Sun, 15 Mar 2026 21:07:50] INFO Reading /tmp/tmpzyinltmc/output.35439375._000082.root for sample zee
 [Sun, 15 Mar 2026 21:07:50] INFO Reading /tmp/tmpzyinltmc/output.35439375._000081.root for sample zee
 [Sun, 15 Mar 2026 21:07:50] INFO Reading /tmp/tmpzyinltmc/output.35439375._000088.root for sample zee
 [Sun, 15 Mar 2026 21:07:51] INFO Reading /tmp/tmpzyinltmc/output.35439375._000080.root for sample zee
 [Sun, 15 Mar 2026 21:07:51] INFO Reading /tmp/tmpzyinltmc/output.35439375._000091.root for sample zee
 [Sun, 15 Mar 2026 21:07:51] INFO Reading /tmp/tmpzyinltmc/output.35439375._000071.root for sample zee
 [Sun, 15 Mar 2026 21:07:51] INFO Reading /tmp/tmpzyinltmc/output.35439375._000076.root for sample zee
 [Sun, 15 Mar 2026 21:07:51] INFO Reading /tmp/tmpzyinltmc/output.35439375._000089.root for sample zee
 [Sun, 15 Mar 2026 21:07:52] INFO Reading /tmp/tmpzyinltmc/output.35439375._000069.root for sample zee
 [Sun, 15 Mar 2026 21:07:52] INFO Reading /tmp/tmpzyinltmc/output.35439375._000086.root for sample zee
 [Sun, 15 Mar 2026 21:07:52] INFO Reading /tmp/tmpzyinltmc/output.35439375._000079.root for sample zee
 [Sun, 15 Mar 2026 21:07:52] INFO Reading /tmp/tmpzyinltmc/output.35439375._000087.root for sample zee
 [Sun, 15 Mar 2026 21:07:52] INFO Reading /tmp/tmpzyinltmc/output.35439375._000092.root for sample zee
 [Sun, 15 Mar 2026 21:07:52] INFO Reading /tmp/tmpzyinltmc/output.35439375._000074.root for sample zee
 [Sun, 15 Mar 2026 21:07:53] INFO Reading /tmp/tmpzyinltmc/output.35439375._000068.root for sample zee
 [Sun, 15 Mar 2026 21:07:53] INFO Reading /tmp/tmpzyinltmc/output.35439375._000083.root for sample zee
 [Sun, 15 Mar 2026 21:07:53] INFO Reading /tmp/tmpzyinltmc/output.35439375._000073.root for sample zee
 [Sun, 15 Mar 2026 21:07:53] INFO Reading /tmp/tmpzyinltmc/output.35439375._000070.root for sample zee
 [Sun, 15 Mar 2026 21:07:53] INFO Reading /tmp/tmpzyinltmc/output.35439375._000090.root for sample zee
 [Sun, 15 Mar 2026 21:07:54] INFO Reading /tmp/tmpzyinltmc/output.35439375._000085.root for sample zee
 [Sun, 15 Mar 2026 21:07:54] INFO Reading /tmp/tmpzyinltmc/output.35439375._000075.root for sample zee
 [Sun, 15 Mar 2026 21:07:54] INFO Reading /tmp/tmpzyinltmc/output.35439375._000072.root for sample zee
 [Sun, 15 Mar 2026 21:07:54] INFO Reading /tmp/tmpzyinltmc/output.35439375._000077.root for sample zee

Processing Batch 52 (Rows 5293157 to 5393465)

 [Sun, 15 Mar 2026 21:07:55] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000009.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:07:56] INFO Reading /tmp/tmpzgxragvg/output.35439375._000168.root for sample zee
 [Sun, 15 Mar 2026 21:07:56] INFO Reading /tmp/tmpzgxragvg/output.35439375._000157.root for sample zee
 [Sun, 15 Mar 2026 21:07:56] INFO Reading /tmp/tmpzgxragvg/output.35439375._000153.root for sample zee
 [Sun, 15 Mar 2026 21:07:56] INFO Reading /tmp/tmpzgxragvg/output.35439375._000167.root for sample zee
 [Sun, 15 Mar 2026 21:07:56] INFO Reading /tmp/tmpzgxragvg/output.35439375._000156.root for sample zee
 [Sun, 15 Mar 2026 21:07:56] INFO Reading /tmp/tmpzgxragvg/output.35439375._000161.root for sample zee
 [Sun, 15 Mar 2026 21:07:57] INFO Reading /tmp/tmpzgxragvg/output.35439375._000164.root for sample zee
 [Sun, 15 Mar 2026 21:07:57] INFO Reading /tmp/tmpzgxragvg/output.35439375._000173.root for sample zee
 [Sun, 15 Mar 2026 21:07:57] INFO Reading /tmp/tmpzgxragvg/output.35439375._000169.root for sample zee
 [Sun, 15 Mar 2026 21:07:57] INFO Reading /tmp/tmpzgxragvg/output.35439375._000159.root for sample zee
 [Sun, 15 Mar 2026 21:07:57] INFO Reading /tmp/tmpzgxragvg/output.35439375._000150.root for sample zee
 [Sun, 15 Mar 2026 21:07:57] INFO Reading /tmp/tmpzgxragvg/output.35439375._000154.root for sample zee
 [Sun, 15 Mar 2026 21:07:58] INFO Reading /tmp/tmpzgxragvg/output.35439375._000160.root for sample zee
 [Sun, 15 Mar 2026 21:07:58] INFO Reading /tmp/tmpzgxragvg/output.35439375._000166.root for sample zee
 [Sun, 15 Mar 2026 21:07:58] INFO Reading /tmp/tmpzgxragvg/output.35439375._000174.root for sample zee
 [Sun, 15 Mar 2026 21:07:58] INFO Reading /tmp/tmpzgxragvg/output.35439375._000151.root for sample zee
 [Sun, 15 Mar 2026 21:07:58] INFO Reading /tmp/tmpzgxragvg/output.35439375._000162.root for sample zee
 [Sun, 15 Mar 2026 21:07:59] INFO Reading /tmp/tmpzgxragvg/output.35439375._000171.root for sample zee
 [Sun, 15 Mar 2026 21:07:59] INFO Reading /tmp/tmpzgxragvg/output.35439375._000158.root for sample zee
 [Sun, 15 Mar 2026 21:07:59] INFO Reading /tmp/tmpzgxragvg/output.35439375._000172.root for sample zee
 [Sun, 15 Mar 2026 21:07:59] INFO Reading /tmp/tmpzgxragvg/output.35439375._000163.root for sample zee
 [Sun, 15 Mar 2026 21:07:59] INFO Reading /tmp/tmpzgxragvg/output.35439375._000155.root for sample zee
 [Sun, 15 Mar 2026 21:08:00] INFO Reading /tmp/tmpzgxragvg/output.35439375._000152.root for sample zee

Processing Batch 53 (Rows 5393465 to 5494532)

 [Sun, 15 Mar 2026 21:08:01] INFO Reading /tmp/tmpzgxragvg/output.35439375._000165.root for sample zee
 [Sun, 15 Mar 2026 21:08:01] INFO Reading /tmp/tmpzgxragvg/output.35439375._000170.root for sample zee
 [Sun, 15 Mar 2026 21:08:01] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000010.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:08:02] INFO Reading /tmp/tmptb70lsfj/output.35439375._000115.root for sample zee
 [Sun, 15 Mar 2026 21:08:02] INFO Reading /tmp/tmptb70lsfj/output.35439375._000116.root for sample zee
 [Sun, 15 Mar 2026 21:08:02] INFO Reading /tmp/tmptb70lsfj/output.35439375._000125.root for sample zee
 [Sun, 15 Mar 2026 21:08:03] INFO Reading /tmp/tmptb70lsfj/output.35439375._000132.root for sample zee
 [Sun, 15 Mar 2026 21:08:03] INFO Reading /tmp/tmptb70lsfj/output.35439375._000103.root for sample zee
 [Sun, 15 Mar 2026 21:08:03] INFO Reading /tmp/tmptb70lsfj/output.35439375._000148.root for sample zee
 [Sun, 15 Mar 2026 21:08:03] INFO Reading /tmp/tmptb70lsfj/output.35439375._000142.root for sample zee
 [Sun, 15 Mar 2026 21:08:03] INFO Reading /tmp/tmptb70lsfj/output.35439375._000149.root for sample zee
 [Sun, 15 Mar 2026 21:08:03] INFO Reading /tmp/tmptb70lsfj/output.35439375._000117.root for sample zee
 [Sun, 15 Mar 2026 21:08:04] INFO Reading /tmp/tmptb70lsfj/output.35439375._000109.root for sample zee
 [Sun, 15 Mar 2026 21:08:04] INFO Reading /tmp/tmptb70lsfj/output.35439375._000145.root for sample zee
 [Sun, 15 Mar 2026 21:08:04] INFO Reading /tmp/tmptb70lsfj/output.35439375._000137.root for sample zee
 [Sun, 15 Mar 2026 21:08:04] INFO Reading /tmp/tmptb70lsfj/output.35439375._000135.root for sample zee
 [Sun, 15 Mar 2026 21:08:04] INFO Reading /tmp/tmptb70lsfj/output.35439375._000127.root for sample zee
 [Sun, 15 Mar 2026 21:08:04] INFO Reading /tmp/tmptb70lsfj/output.35439375._000126.root for sample zee
 [Sun, 15 Mar 2026 21:08:05] INFO Reading /tmp/tmptb70lsfj/output.35439375._000143.root for sample zee
 [Sun, 15 Mar 2026 21:08:05] INFO Reading /tmp/tmptb70lsfj/output.35439375._000108.root for sample zee
 [Sun, 15 Mar 2026 21:08:05] INFO Reading /tmp/tmptb70lsfj/output.35439375._000120.root for sample zee
 [Sun, 15 Mar 2026 21:08:05] INFO Reading /tmp/tmptb70lsfj/output.35439375._000131.root for sample zee
 [Sun, 15 Mar 2026 21:08:05] INFO Reading /tmp/tmptb70lsfj/output.35439375._000106.root for sample zee
 [Sun, 15 Mar 2026 21:08:06] INFO Reading /tmp/tmptb70lsfj/output.35439375._000112.root for sample zee

Processing Batch 54 (Rows 5494532 to 5595273)

 [Sun, 15 Mar 2026 21:08:07] INFO Reading /tmp/tmptb70lsfj/output.35439375._000128.root for sample zee
 [Sun, 15 Mar 2026 21:08:07] INFO Reading /tmp/tmptb70lsfj/output.35439375._000138.root for sample zee
 [Sun, 15 Mar 2026 21:08:07] INFO Reading /tmp/tmptb70lsfj/output.35439375._000123.root for sample zee
 [Sun, 15 Mar 2026 21:08:07] INFO Reading /tmp/tmptb70lsfj/output.35439375._000141.root for sample zee
 [Sun, 15 Mar 2026 21:08:07] INFO Reading /tmp/tmptb70lsfj/output.35439375._000121.root for sample zee
 [Sun, 15 Mar 2026 21:08:07] INFO Reading /tmp/tmptb70lsfj/output.35439375._000133.root for sample zee
 [Sun, 15 Mar 2026 21:08:08] INFO Reading /tmp/tmptb70lsfj/output.35439375._000134.root for sample zee
 [Sun, 15 Mar 2026 21:08:08] INFO Reading /tmp/tmptb70lsfj/output.35439375._000105.root for sample zee
 [Sun, 15 Mar 2026 21:08:08] INFO Reading /tmp/tmptb70lsfj/output.35439375._000118.root for sample zee
 [Sun, 15 Mar 2026 21:08:08] INFO Reading /tmp/tmptb70lsfj/output.35439375._000146.root for sample zee
 [Sun, 15 Mar 2026 21:08:08] INFO Reading /tmp/tmptb70lsfj/output.35439375._000129.root for sample zee
 [Sun, 15 Mar 2026 21:08:08] INFO Reading /tmp/tmptb70lsfj/output.35439375._000140.root for sample zee
 [Sun, 15 Mar 2026 21:08:09] INFO Reading /tmp/tmptb70lsfj/output.35439375._000111.root for sample zee
 [Sun, 15 Mar 2026 21:08:09] INFO Reading /tmp/tmptb70lsfj/output.35439375._000122.root for sample zee
 [Sun, 15 Mar 2026 21:08:09] INFO Reading /tmp/tmptb70lsfj/output.35439375._000101.root for sample zee
 [Sun, 15 Mar 2026 21:08:09] INFO Reading /tmp/tmptb70lsfj/output.35439375._000136.root for sample zee
 [Sun, 15 Mar 2026 21:08:09] INFO Reading /tmp/tmptb70lsfj/output.35439375._000102.root for sample zee
 [Sun, 15 Mar 2026 21:08:10] INFO Reading /tmp/tmptb70lsfj/output.35439375._000110.root for sample zee
 [Sun, 15 Mar 2026 21:08:10] INFO Reading /tmp/tmptb70lsfj/output.35439375._000104.root for sample zee
 [Sun, 15 Mar 2026 21:08:10] INFO Reading /tmp/tmptb70lsfj/output.35439375._000100.root for sample zee
 [Sun, 15 Mar 2026 21:08:10] INFO Reading /tmp/tmptb70lsfj/output.35439375._000124.root for sample zee
 [Sun, 15 Mar 2026 21:08:10] INFO Reading /tmp/tmptb70lsfj/output.35439375._000114.root for sample zee
 [Sun, 15 Mar 2026 21:08:11] INFO Reading /tmp/tmptb70lsfj/output.35439375._000113.root for sample zee

Processing Batch 55 (Rows 5595273 to 5696107)

 [Sun, 15 Mar 2026 21:08:12] INFO Reading /tmp/tmptb70lsfj/output.35439375._000119.root for sample zee
 [Sun, 15 Mar 2026 21:08:12] INFO Reading /tmp/tmptb70lsfj/output.35439375._000147.root for sample zee
 [Sun, 15 Mar 2026 21:08:12] INFO Reading /tmp/tmptb70lsfj/output.35439375._000144.root for sample zee
 [Sun, 15 Mar 2026 21:08:12] INFO Reading /tmp/tmptb70lsfj/output.35439375._000139.root for sample zee
 [Sun, 15 Mar 2026 21:08:12] INFO Reading /tmp/tmptb70lsfj/output.35439375._000107.root for sample zee
 [Sun, 15 Mar 2026 21:08:13] INFO Reading /tmp/tmptb70lsfj/output.35439375._000130.root for sample zee
 [Sun, 15 Mar 2026 21:08:13] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000011.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:08:14] INFO Reading /tmp/tmpi5egob5l/output.35439375._000210.root for sample zee
 [Sun, 15 Mar 2026 21:08:14] INFO Reading /tmp/tmpi5egob5l/output.35439375._000207.root for sample zee
 [Sun, 15 Mar 2026 21:08:14] INFO Reading /tmp/tmpi5egob5l/output.35439375._000190.root for sample zee
 [Sun, 15 Mar 2026 21:08:14] INFO Reading /tmp/tmpi5egob5l/output.35439375._000211.root for sample zee
 [Sun, 15 Mar 2026 21:08:15] INFO Reading /tmp/tmpi5egob5l/output.35439375._000199.root for sample zee
 [Sun, 15 Mar 2026 21:08:15] INFO Reading /tmp/tmpi5egob5l/output.35439375._000198.root for sample zee
 [Sun, 15 Mar 2026 21:08:15] INFO Reading /tmp/tmpi5egob5l/output.35439375._000197.root for sample zee
 [Sun, 15 Mar 2026 21:08:15] INFO Reading /tmp/tmpi5egob5l/output.35439375._000205.root for sample zee
 [Sun, 15 Mar 2026 21:08:15] INFO Reading /tmp/tmpi5egob5l/output.35439375._000223.root for sample zee
 [Sun, 15 Mar 2026 21:08:16] INFO Reading /tmp/tmpi5egob5l/output.35439375._000215.root for sample zee
 [Sun, 15 Mar 2026 21:08:16] INFO Reading /tmp/tmpi5egob5l/output.35439375._000195.root for sample zee
 [Sun, 15 Mar 2026 21:08:16] INFO Reading /tmp/tmpi5egob5l/output.35439375._000186.root for sample zee
 [Sun, 15 Mar 2026 21:08:16] INFO Reading /tmp/tmpi5egob5l/output.35439375._000193.root for sample zee
 [Sun, 15 Mar 2026 21:08:16] INFO Reading /tmp/tmpi5egob5l/output.35439375._000209.root for sample zee
 [Sun, 15 Mar 2026 21:08:17] INFO Reading /tmp/tmpi5egob5l/output.35439375._000188.root for sample zee
 [Sun, 15 Mar 2026 21:08:17] INFO Reading /tmp/tmpi5egob5l/output.35439375._000180.root for sample zee
 [Sun, 15 Mar 2026 21:08:17] INFO Reading /tmp/tmpi5egob5l/output.35439375._000222.root for sample zee

Processing Batch 56 (Rows 5696107 to 5796871)

 [Sun, 15 Mar 2026 21:08:18] INFO Reading /tmp/tmpi5egob5l/output.35439375._000208.root for sample zee
 [Sun, 15 Mar 2026 21:08:18] INFO Reading /tmp/tmpi5egob5l/output.35439375._000224.root for sample zee
 [Sun, 15 Mar 2026 21:08:18] INFO Reading /tmp/tmpi5egob5l/output.35439375._000204.root for sample zee
 [Sun, 15 Mar 2026 21:08:19] INFO Reading /tmp/tmpi5egob5l/output.35439375._000191.root for sample zee
 [Sun, 15 Mar 2026 21:08:19] INFO Reading /tmp/tmpi5egob5l/output.35439375._000175.root for sample zee
 [Sun, 15 Mar 2026 21:08:19] INFO Reading /tmp/tmpi5egob5l/output.35439375._000194.root for sample zee
 [Sun, 15 Mar 2026 21:08:19] INFO Reading /tmp/tmpi5egob5l/output.35439375._000192.root for sample zee
 [Sun, 15 Mar 2026 21:08:19] INFO Reading /tmp/tmpi5egob5l/output.35439375._000203.root for sample zee
 [Sun, 15 Mar 2026 21:08:20] INFO Reading /tmp/tmpi5egob5l/output.35439375._000200.root for sample zee
 [Sun, 15 Mar 2026 21:08:20] INFO Reading /tmp/tmpi5egob5l/output.35439375._000183.root for sample zee
 [Sun, 15 Mar 2026 21:08:20] INFO Reading /tmp/tmpi5egob5l/output.35439375._000217.root for sample zee
 [Sun, 15 Mar 2026 21:08:20] INFO Reading /tmp/tmpi5egob5l/output.35439375._000189.root for sample zee
 [Sun, 15 Mar 2026 21:08:20] INFO Reading /tmp/tmpi5egob5l/output.35439375._000187.root for sample zee
 [Sun, 15 Mar 2026 21:08:20] INFO Reading /tmp/tmpi5egob5l/output.35439375._000212.root for sample zee
 [Sun, 15 Mar 2026 21:08:21] INFO Reading /tmp/tmpi5egob5l/output.35439375._000176.root for sample zee
 [Sun, 15 Mar 2026 21:08:21] INFO Reading /tmp/tmpi5egob5l/output.35439375._000220.root for sample zee
 [Sun, 15 Mar 2026 21:08:21] INFO Reading /tmp/tmpi5egob5l/output.35439375._000177.root for sample zee
 [Sun, 15 Mar 2026 21:08:21] INFO Reading /tmp/tmpi5egob5l/output.35439375._000196.root for sample zee
 [Sun, 15 Mar 2026 21:08:21] INFO Reading /tmp/tmpi5egob5l/output.35439375._000184.root for sample zee
 [Sun, 15 Mar 2026 21:08:22] INFO Reading /tmp/tmpi5egob5l/output.35439375._000218.root for sample zee
 [Sun, 15 Mar 2026 21:08:22] INFO Reading /tmp/tmpi5egob5l/output.35439375._000221.root for sample zee
 [Sun, 15 Mar 2026 21:08:22] INFO Reading /tmp/tmpi5egob5l/output.35439375._000179.root for sample zee
 [Sun, 15 Mar 2026 21:08:22] INFO Reading /tmp/tmpi5egob5l/output.35439375._000178.root for sample zee

Processing Batch 57 (Rows 5796871 to 5897120)

 [Sun, 15 Mar 2026 21:08:23] INFO Reading /tmp/tmpi5egob5l/output.35439375._000214.root for sample zee
 [Sun, 15 Mar 2026 21:08:24] INFO Reading /tmp/tmpi5egob5l/output.35439375._000202.root for sample zee
 [Sun, 15 Mar 2026 21:08:24] INFO Reading /tmp/tmpi5egob5l/output.35439375._000181.root for sample zee
 [Sun, 15 Mar 2026 21:08:24] INFO Reading /tmp/tmpi5egob5l/output.35439375._000206.root for sample zee
 [Sun, 15 Mar 2026 21:08:24] INFO Reading /tmp/tmpi5egob5l/output.35439375._000216.root for sample zee
 [Sun, 15 Mar 2026 21:08:24] INFO Reading /tmp/tmpi5egob5l/output.35439375._000213.root for sample zee
 [Sun, 15 Mar 2026 21:08:25] INFO Reading /tmp/tmpi5egob5l/output.35439375._000219.root for sample zee
 [Sun, 15 Mar 2026 21:08:25] INFO Reading /tmp/tmpi5egob5l/output.35439375._000182.root for sample zee
 [Sun, 15 Mar 2026 21:08:25] INFO Reading /tmp/tmpi5egob5l/output.35439375._000185.root for sample zee
 [Sun, 15 Mar 2026 21:08:25] INFO Reading /tmp/tmpi5egob5l/output.35439375._000201.root for sample zee
 [Sun, 15 Mar 2026 21:08:25] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000012.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:08:26] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000267.root for sample zee
 [Sun, 15 Mar 2026 21:08:26] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000246.root for sample zee
 [Sun, 15 Mar 2026 21:08:27] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000258.root for sample zee
 [Sun, 15 Mar 2026 21:08:27] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000234.root for sample zee
 [Sun, 15 Mar 2026 21:08:27] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000244.root for sample zee
 [Sun, 15 Mar 2026 21:08:27] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000240.root for sample zee
 [Sun, 15 Mar 2026 21:08:27] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000249.root for sample zee
 [Sun, 15 Mar 2026 21:08:27] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000251.root for sample zee
 [Sun, 15 Mar 2026 21:08:28] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000268.root for sample zee
 [Sun, 15 Mar 2026 21:08:28] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000254.root for sample zee
 [Sun, 15 Mar 2026 21:08:28] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000263.root for sample zee
 [Sun, 15 Mar 2026 21:08:28] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000259.root for sample zee
 [Sun, 15 Mar 2026 21:08:28] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000245.root for sample zee

Processing Batch 58 (Rows 5897120 to 5998622)

 [Sun, 15 Mar 2026 21:08:29] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000230.root for sample zee
 [Sun, 15 Mar 2026 21:08:29] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000252.root for sample zee
 [Sun, 15 Mar 2026 21:08:30] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000242.root for sample zee
 [Sun, 15 Mar 2026 21:08:30] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000233.root for sample zee
 [Sun, 15 Mar 2026 21:08:30] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000236.root for sample zee
 [Sun, 15 Mar 2026 21:08:30] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000227.root for sample zee
 [Sun, 15 Mar 2026 21:08:30] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000272.root for sample zee
 [Sun, 15 Mar 2026 21:08:31] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000274.root for sample zee
 [Sun, 15 Mar 2026 21:08:31] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000243.root for sample zee
 [Sun, 15 Mar 2026 21:08:31] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000256.root for sample zee
 [Sun, 15 Mar 2026 21:08:31] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000271.root for sample zee
 [Sun, 15 Mar 2026 21:08:31] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000250.root for sample zee
 [Sun, 15 Mar 2026 21:08:31] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000255.root for sample zee
 [Sun, 15 Mar 2026 21:08:32] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000253.root for sample zee
 [Sun, 15 Mar 2026 21:08:32] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000269.root for sample zee
 [Sun, 15 Mar 2026 21:08:32] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000261.root for sample zee
 [Sun, 15 Mar 2026 21:08:32] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000248.root for sample zee
 [Sun, 15 Mar 2026 21:08:32] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000257.root for sample zee
 [Sun, 15 Mar 2026 21:08:32] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000273.root for sample zee
 [Sun, 15 Mar 2026 21:08:33] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000237.root for sample zee
 [Sun, 15 Mar 2026 21:08:33] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000229.root for sample zee
 [Sun, 15 Mar 2026 21:08:33] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000225.root for sample zee
 [Sun, 15 Mar 2026 21:08:33] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000264.root for sample zee

Processing Batch 59 (Rows 5998622 to 6099583)

 [Sun, 15 Mar 2026 21:08:34] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000247.root for sample zee
 [Sun, 15 Mar 2026 21:08:35] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000226.root for sample zee
 [Sun, 15 Mar 2026 21:08:35] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000231.root for sample zee
 [Sun, 15 Mar 2026 21:08:35] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000270.root for sample zee
 [Sun, 15 Mar 2026 21:08:35] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000239.root for sample zee
 [Sun, 15 Mar 2026 21:08:35] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000265.root for sample zee
 [Sun, 15 Mar 2026 21:08:35] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000262.root for sample zee
 [Sun, 15 Mar 2026 21:08:36] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000241.root for sample zee
 [Sun, 15 Mar 2026 21:08:36] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000266.root for sample zee
 [Sun, 15 Mar 2026 21:08:36] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000232.root for sample zee
 [Sun, 15 Mar 2026 21:08:36] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000235.root for sample zee
 [Sun, 15 Mar 2026 21:08:36] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000260.root for sample zee
 [Sun, 15 Mar 2026 21:08:37] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000238.root for sample zee
 [Sun, 15 Mar 2026 21:08:37] INFO Reading /tmp/tmpnjh1gob0/output.35439375._000228.root for sample zee
 [Sun, 15 Mar 2026 21:08:37] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000013.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:08:38] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000279.root for sample zee
 [Sun, 15 Mar 2026 21:08:38] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000296.root for sample zee
 [Sun, 15 Mar 2026 21:08:38] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000292.root for sample zee
 [Sun, 15 Mar 2026 21:08:38] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000314.root for sample zee
 [Sun, 15 Mar 2026 21:08:38] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000317.root for sample zee
 [Sun, 15 Mar 2026 21:08:39] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000285.root for sample zee
 [Sun, 15 Mar 2026 21:08:39] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000315.root for sample zee
 [Sun, 15 Mar 2026 21:08:39] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000284.root for sample zee
 [Sun, 15 Mar 2026 21:08:39] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000278.root for sample zee

Processing Batch 60 (Rows 6099583 to 6200966)

 [Sun, 15 Mar 2026 21:08:40] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000275.root for sample zee
 [Sun, 15 Mar 2026 21:08:40] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000301.root for sample zee
 [Sun, 15 Mar 2026 21:08:41] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000323.root for sample zee
 [Sun, 15 Mar 2026 21:08:41] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000283.root for sample zee
 [Sun, 15 Mar 2026 21:08:41] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000288.root for sample zee
 [Sun, 15 Mar 2026 21:08:41] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000299.root for sample zee
 [Sun, 15 Mar 2026 21:08:41] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000302.root for sample zee
 [Sun, 15 Mar 2026 21:08:41] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000289.root for sample zee
 [Sun, 15 Mar 2026 21:08:42] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000310.root for sample zee
 [Sun, 15 Mar 2026 21:08:42] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000321.root for sample zee
 [Sun, 15 Mar 2026 21:08:42] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000276.root for sample zee
 [Sun, 15 Mar 2026 21:08:42] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000324.root for sample zee
 [Sun, 15 Mar 2026 21:08:42] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000293.root for sample zee
 [Sun, 15 Mar 2026 21:08:42] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000281.root for sample zee
 [Sun, 15 Mar 2026 21:08:43] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000320.root for sample zee
 [Sun, 15 Mar 2026 21:08:43] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000295.root for sample zee
 [Sun, 15 Mar 2026 21:08:43] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000309.root for sample zee
 [Sun, 15 Mar 2026 21:08:43] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000312.root for sample zee
 [Sun, 15 Mar 2026 21:08:43] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000291.root for sample zee
 [Sun, 15 Mar 2026 21:08:44] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000322.root for sample zee
 [Sun, 15 Mar 2026 21:08:44] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000286.root for sample zee
 [Sun, 15 Mar 2026 21:08:44] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000297.root for sample zee
 [Sun, 15 Mar 2026 21:08:44] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000287.root for sample zee

Processing Batch 61 (Rows 6200966 to 6302129)

 [Sun, 15 Mar 2026 21:08:45] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000311.root for sample zee
 [Sun, 15 Mar 2026 21:08:45] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000316.root for sample zee
 [Sun, 15 Mar 2026 21:08:45] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000306.root for sample zee
 [Sun, 15 Mar 2026 21:08:46] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000318.root for sample zee
 [Sun, 15 Mar 2026 21:08:46] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000300.root for sample zee
 [Sun, 15 Mar 2026 21:08:46] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000294.root for sample zee
 [Sun, 15 Mar 2026 21:08:46] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000277.root for sample zee
 [Sun, 15 Mar 2026 21:08:46] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000319.root for sample zee
 [Sun, 15 Mar 2026 21:08:46] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000313.root for sample zee
 [Sun, 15 Mar 2026 21:08:47] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000307.root for sample zee
 [Sun, 15 Mar 2026 21:08:47] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000282.root for sample zee
 [Sun, 15 Mar 2026 21:08:47] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000280.root for sample zee
 [Sun, 15 Mar 2026 21:08:47] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000303.root for sample zee
 [Sun, 15 Mar 2026 21:08:47] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000304.root for sample zee
 [Sun, 15 Mar 2026 21:08:47] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000298.root for sample zee
 [Sun, 15 Mar 2026 21:08:48] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000308.root for sample zee
 [Sun, 15 Mar 2026 21:08:48] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000305.root for sample zee
 [Sun, 15 Mar 2026 21:08:48] INFO Reading /tmp/tmpmvfno5v8/output.35439375._000290.root for sample zee
 [Sun, 15 Mar 2026 21:08:48] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000014.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:08:49] INFO Reading /tmp/tmprmyiml2g/output.35439375._000350.root for sample zee
 [Sun, 15 Mar 2026 21:08:49] INFO Reading /tmp/tmprmyiml2g/output.35439375._000344.root for sample zee
 [Sun, 15 Mar 2026 21:08:49] INFO Reading /tmp/tmprmyiml2g/output.35439375._000327.root for sample zee
 [Sun, 15 Mar 2026 21:08:49] INFO Reading /tmp/tmprmyiml2g/output.35439375._000357.root for sample zee
 [Sun, 15 Mar 2026 21:08:50] INFO Reading /tmp/tmprmyiml2g/output.35439375._000348.root for sample zee

Processing Batch 62 (Rows 6302129 to 6403514)

 [Sun, 15 Mar 2026 21:08:51] INFO Reading /tmp/tmprmyiml2g/output.35439375._000335.root for sample zee
 [Sun, 15 Mar 2026 21:08:51] INFO Reading /tmp/tmprmyiml2g/output.35439375._000352.root for sample zee
 [Sun, 15 Mar 2026 21:08:51] INFO Reading /tmp/tmprmyiml2g/output.35439375._000351.root for sample zee
 [Sun, 15 Mar 2026 21:08:51] INFO Reading /tmp/tmprmyiml2g/output.35439375._000365.root for sample zee
 [Sun, 15 Mar 2026 21:08:51] INFO Reading /tmp/tmprmyiml2g/output.35439375._000328.root for sample zee
 [Sun, 15 Mar 2026 21:08:51] INFO Reading /tmp/tmprmyiml2g/output.35439375._000356.root for sample zee
 [Sun, 15 Mar 2026 21:08:52] INFO Reading /tmp/tmprmyiml2g/output.35439375._000337.root for sample zee
 [Sun, 15 Mar 2026 21:08:52] INFO Reading /tmp/tmprmyiml2g/output.35439375._000325.root for sample zee
 [Sun, 15 Mar 2026 21:08:52] INFO Reading /tmp/tmprmyiml2g/output.35439375._000368.root for sample zee
 [Sun, 15 Mar 2026 21:08:52] INFO Reading /tmp/tmprmyiml2g/output.35439375._000361.root for sample zee
 [Sun, 15 Mar 2026 21:08:52] INFO Reading /tmp/tmprmyiml2g/output.35439375._000326.root for sample zee
 [Sun, 15 Mar 2026 21:08:52] INFO Reading /tmp/tmprmyiml2g/output.35439375._000363.root for sample zee
 [Sun, 15 Mar 2026 21:08:53] INFO Reading /tmp/tmprmyiml2g/output.35439375._000367.root for sample zee
 [Sun, 15 Mar 2026 21:08:53] INFO Reading /tmp/tmprmyiml2g/output.35439375._000362.root for sample zee
 [Sun, 15 Mar 2026 21:08:53] INFO Reading /tmp/tmprmyiml2g/output.35439375._000334.root for sample zee
 [Sun, 15 Mar 2026 21:08:53] INFO Reading /tmp/tmprmyiml2g/output.35439375._000331.root for sample zee
 [Sun, 15 Mar 2026 21:08:53] INFO Reading /tmp/tmprmyiml2g/output.35439375._000355.root for sample zee
 [Sun, 15 Mar 2026 21:08:54] INFO Reading /tmp/tmprmyiml2g/output.35439375._000341.root for sample zee
 [Sun, 15 Mar 2026 21:08:54] INFO Reading /tmp/tmprmyiml2g/output.35439375._000345.root for sample zee
 [Sun, 15 Mar 2026 21:08:54] INFO Reading /tmp/tmprmyiml2g/output.35439375._000333.root for sample zee
 [Sun, 15 Mar 2026 21:08:54] INFO Reading /tmp/tmprmyiml2g/output.35439375._000329.root for sample zee
 [Sun, 15 Mar 2026 21:08:54] INFO Reading /tmp/tmprmyiml2g/output.35439375._000364.root for sample zee
 [Sun, 15 Mar 2026 21:08:54] INFO Reading /tmp/tmprmyiml2g/output.35439375._000354.root for sample zee

Processing Batch 63 (Rows 6403514 to 6504526)

 [Sun, 15 Mar 2026 21:08:55] INFO Reading /tmp/tmprmyiml2g/output.35439375._000349.root for sample zee
 [Sun, 15 Mar 2026 21:08:56] INFO Reading /tmp/tmprmyiml2g/output.35439375._000359.root for sample zee
 [Sun, 15 Mar 2026 21:08:56] INFO Reading /tmp/tmprmyiml2g/output.35439375._000336.root for sample zee
 [Sun, 15 Mar 2026 21:08:56] INFO Reading /tmp/tmprmyiml2g/output.35439375._000330.root for sample zee
 [Sun, 15 Mar 2026 21:08:56] INFO Reading /tmp/tmprmyiml2g/output.35439375._000372.root for sample zee
 [Sun, 15 Mar 2026 21:08:56] INFO Reading /tmp/tmprmyiml2g/output.35439375._000371.root for sample zee
 [Sun, 15 Mar 2026 21:08:56] INFO Reading /tmp/tmprmyiml2g/output.35439375._000332.root for sample zee
 [Sun, 15 Mar 2026 21:08:57] INFO Reading /tmp/tmprmyiml2g/output.35439375._000339.root for sample zee
 [Sun, 15 Mar 2026 21:08:57] INFO Reading /tmp/tmprmyiml2g/output.35439375._000360.root for sample zee
 [Sun, 15 Mar 2026 21:08:57] INFO Reading /tmp/tmprmyiml2g/output.35439375._000346.root for sample zee
 [Sun, 15 Mar 2026 21:08:57] INFO Reading /tmp/tmprmyiml2g/output.35439375._000366.root for sample zee
 [Sun, 15 Mar 2026 21:08:57] INFO Reading /tmp/tmprmyiml2g/output.35439375._000343.root for sample zee
 [Sun, 15 Mar 2026 21:08:57] INFO Reading /tmp/tmprmyiml2g/output.35439375._000342.root for sample zee
 [Sun, 15 Mar 2026 21:08:58] INFO Reading /tmp/tmprmyiml2g/output.35439375._000347.root for sample zee
 [Sun, 15 Mar 2026 21:08:58] INFO Reading /tmp/tmprmyiml2g/output.35439375._000374.root for sample zee
 [Sun, 15 Mar 2026 21:08:58] INFO Reading /tmp/tmprmyiml2g/output.35439375._000373.root for sample zee
 [Sun, 15 Mar 2026 21:08:58] INFO Reading /tmp/tmprmyiml2g/output.35439375._000358.root for sample zee
 [Sun, 15 Mar 2026 21:08:58] INFO Reading /tmp/tmprmyiml2g/output.35439375._000353.root for sample zee
 [Sun, 15 Mar 2026 21:08:59] INFO Reading /tmp/tmprmyiml2g/output.35439375._000370.root for sample zee
 [Sun, 15 Mar 2026 21:08:59] INFO Reading /tmp/tmprmyiml2g/output.35439375._000340.root for sample zee
 [Sun, 15 Mar 2026 21:08:59] INFO Reading /tmp/tmprmyiml2g/output.35439375._000369.root for sample zee
 [Sun, 15 Mar 2026 21:08:59] INFO Reading /tmp/tmprmyiml2g/output.35439375._000338.root for sample zee
 [Sun, 15 Mar 2026 21:08:59] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000015.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:00] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000407.root for sample zee

Processing Batch 64 (Rows 6504526 to 6605649)

 [Sun, 15 Mar 2026 21:09:01] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000388.root for sample zee
 [Sun, 15 Mar 2026 21:09:01] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000404.root for sample zee
 [Sun, 15 Mar 2026 21:09:01] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000377.root for sample zee
 [Sun, 15 Mar 2026 21:09:02] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000409.root for sample zee
 [Sun, 15 Mar 2026 21:09:02] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000396.root for sample zee
 [Sun, 15 Mar 2026 21:09:02] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000424.root for sample zee
 [Sun, 15 Mar 2026 21:09:02] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000393.root for sample zee
 [Sun, 15 Mar 2026 21:09:02] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000380.root for sample zee
 [Sun, 15 Mar 2026 21:09:02] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000391.root for sample zee
 [Sun, 15 Mar 2026 21:09:03] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000397.root for sample zee
 [Sun, 15 Mar 2026 21:09:03] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000381.root for sample zee
 [Sun, 15 Mar 2026 21:09:03] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000390.root for sample zee
 [Sun, 15 Mar 2026 21:09:03] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000400.root for sample zee
 [Sun, 15 Mar 2026 21:09:03] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000392.root for sample zee
 [Sun, 15 Mar 2026 21:09:03] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000403.root for sample zee
 [Sun, 15 Mar 2026 21:09:04] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000382.root for sample zee
 [Sun, 15 Mar 2026 21:09:04] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000419.root for sample zee
 [Sun, 15 Mar 2026 21:09:04] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000389.root for sample zee
 [Sun, 15 Mar 2026 21:09:04] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000383.root for sample zee
 [Sun, 15 Mar 2026 21:09:04] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000387.root for sample zee
 [Sun, 15 Mar 2026 21:09:04] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000399.root for sample zee
 [Sun, 15 Mar 2026 21:09:05] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000415.root for sample zee
 [Sun, 15 Mar 2026 21:09:05] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000406.root for sample zee

Processing Batch 65 (Rows 6605649 to 6706577)

 [Sun, 15 Mar 2026 21:09:06] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000386.root for sample zee
 [Sun, 15 Mar 2026 21:09:06] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000423.root for sample zee
 [Sun, 15 Mar 2026 21:09:06] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000375.root for sample zee
 [Sun, 15 Mar 2026 21:09:06] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000411.root for sample zee
 [Sun, 15 Mar 2026 21:09:06] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000401.root for sample zee
 [Sun, 15 Mar 2026 21:09:07] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000378.root for sample zee
 [Sun, 15 Mar 2026 21:09:07] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000416.root for sample zee
 [Sun, 15 Mar 2026 21:09:07] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000420.root for sample zee
 [Sun, 15 Mar 2026 21:09:07] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000414.root for sample zee
 [Sun, 15 Mar 2026 21:09:07] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000385.root for sample zee
 [Sun, 15 Mar 2026 21:09:08] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000394.root for sample zee
 [Sun, 15 Mar 2026 21:09:08] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000405.root for sample zee
 [Sun, 15 Mar 2026 21:09:08] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000395.root for sample zee
 [Sun, 15 Mar 2026 21:09:08] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000410.root for sample zee
 [Sun, 15 Mar 2026 21:09:08] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000412.root for sample zee
 [Sun, 15 Mar 2026 21:09:08] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000408.root for sample zee
 [Sun, 15 Mar 2026 21:09:09] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000402.root for sample zee
 [Sun, 15 Mar 2026 21:09:09] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000398.root for sample zee
 [Sun, 15 Mar 2026 21:09:09] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000376.root for sample zee
 [Sun, 15 Mar 2026 21:09:09] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000422.root for sample zee
 [Sun, 15 Mar 2026 21:09:09] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000421.root for sample zee
 [Sun, 15 Mar 2026 21:09:09] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000417.root for sample zee
 [Sun, 15 Mar 2026 21:09:10] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000384.root for sample zee

Processing Batch 66 (Rows 6706577 to 6807301)

 [Sun, 15 Mar 2026 21:09:11] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000418.root for sample zee
 [Sun, 15 Mar 2026 21:09:11] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000379.root for sample zee
 [Sun, 15 Mar 2026 21:09:11] INFO Reading /tmp/tmpzz5zh54z/output.35439375._000413.root for sample zee
 [Sun, 15 Mar 2026 21:09:11] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000016.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:12] INFO Reading /tmp/tmp70o97fv5/output.35439375._000483.root for sample zee
 [Sun, 15 Mar 2026 21:09:12] INFO Reading /tmp/tmp70o97fv5/output.35439375._000489.root for sample zee
 [Sun, 15 Mar 2026 21:09:12] INFO Reading /tmp/tmp70o97fv5/output.35439375._000491.root for sample zee
 [Sun, 15 Mar 2026 21:09:12] INFO Reading /tmp/tmp70o97fv5/output.35439375._000494.root for sample zee
 [Sun, 15 Mar 2026 21:09:12] INFO Reading /tmp/tmp70o97fv5/output.35439375._000479.root for sample zee
 [Sun, 15 Mar 2026 21:09:12] INFO Reading /tmp/tmp70o97fv5/output.35439375._000481.root for sample zee
 [Sun, 15 Mar 2026 21:09:13] INFO Reading /tmp/tmp70o97fv5/output.35439375._000477.root for sample zee
 [Sun, 15 Mar 2026 21:09:13] INFO Reading /tmp/tmp70o97fv5/output.35439375._000488.root for sample zee
 [Sun, 15 Mar 2026 21:09:13] INFO Reading /tmp/tmp70o97fv5/output.35439375._000490.root for sample zee
 [Sun, 15 Mar 2026 21:09:13] INFO Reading /tmp/tmp70o97fv5/output.35439375._000492.root for sample zee
 [Sun, 15 Mar 2026 21:09:13] INFO Reading /tmp/tmp70o97fv5/output.35439375._000480.root for sample zee
 [Sun, 15 Mar 2026 21:09:13] INFO Reading /tmp/tmp70o97fv5/output.35439375._000475.root for sample zee
 [Sun, 15 Mar 2026 21:09:14] INFO Reading /tmp/tmp70o97fv5/output.35439375._000476.root for sample zee
 [Sun, 15 Mar 2026 21:09:14] INFO Reading /tmp/tmp70o97fv5/output.35439375._000493.root for sample zee
 [Sun, 15 Mar 2026 21:09:14] INFO Reading /tmp/tmp70o97fv5/output.35439375._000478.root for sample zee
 [Sun, 15 Mar 2026 21:09:14] INFO Reading /tmp/tmp70o97fv5/output.35439375._000495.root for sample zee
 [Sun, 15 Mar 2026 21:09:14] INFO Reading /tmp/tmp70o97fv5/output.35439375._000486.root for sample zee
 [Sun, 15 Mar 2026 21:09:15] INFO Reading /tmp/tmp70o97fv5/output.35439375._000484.root for sample zee
 [Sun, 15 Mar 2026 21:09:15] INFO Reading /tmp/tmp70o97fv5/output.35439375._000487.root for sample zee
 [Sun, 15 Mar 2026 21:09:15] INFO Reading /tmp/tmp70o97fv5/output.35439375._000485.root for sample zee

Processing Batch 67 (Rows 6807301 to 6909147)

 [Sun, 15 Mar 2026 21:09:16] INFO Reading /tmp/tmp70o97fv5/output.35439375._000482.root for sample zee
 [Sun, 15 Mar 2026 21:09:16] INFO Reading /tmp/tmp70o97fv5/output.35439375._000496.root for sample zee
 [Sun, 15 Mar 2026 21:09:16] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000017.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:17] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000063.root for sample zee
 [Sun, 15 Mar 2026 21:09:17] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000022.root for sample zee
 [Sun, 15 Mar 2026 21:09:17] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000053.root for sample zee
 [Sun, 15 Mar 2026 21:09:18] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000051.root for sample zee
 [Sun, 15 Mar 2026 21:09:18] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000055.root for sample zee
 [Sun, 15 Mar 2026 21:09:18] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000056.root for sample zee
 [Sun, 15 Mar 2026 21:09:18] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000045.root for sample zee
 [Sun, 15 Mar 2026 21:09:18] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000020.root for sample zee
 [Sun, 15 Mar 2026 21:09:18] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000037.root for sample zee
 [Sun, 15 Mar 2026 21:09:19] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000064.root for sample zee
 [Sun, 15 Mar 2026 21:09:19] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000032.root for sample zee
 [Sun, 15 Mar 2026 21:09:19] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000023.root for sample zee
 [Sun, 15 Mar 2026 21:09:19] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000030.root for sample zee
 [Sun, 15 Mar 2026 21:09:19] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000059.root for sample zee
 [Sun, 15 Mar 2026 21:09:20] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000054.root for sample zee
 [Sun, 15 Mar 2026 21:09:20] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000047.root for sample zee
 [Sun, 15 Mar 2026 21:09:20] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000025.root for sample zee
 [Sun, 15 Mar 2026 21:09:20] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000050.root for sample zee
 [Sun, 15 Mar 2026 21:09:20] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000019.root for sample zee
 [Sun, 15 Mar 2026 21:09:20] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000058.root for sample zee
 [Sun, 15 Mar 2026 21:09:21] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000033.root for sample zee

Processing Batch 68 (Rows 6909147 to 7010336)

 [Sun, 15 Mar 2026 21:09:22] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000052.root for sample zee
 [Sun, 15 Mar 2026 21:09:22] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000060.root for sample zee
 [Sun, 15 Mar 2026 21:09:22] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000029.root for sample zee
 [Sun, 15 Mar 2026 21:09:22] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000048.root for sample zee
 [Sun, 15 Mar 2026 21:09:22] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000038.root for sample zee
 [Sun, 15 Mar 2026 21:09:22] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000035.root for sample zee
 [Sun, 15 Mar 2026 21:09:23] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000044.root for sample zee
 [Sun, 15 Mar 2026 21:09:23] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000027.root for sample zee
 [Sun, 15 Mar 2026 21:09:23] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000057.root for sample zee
 [Sun, 15 Mar 2026 21:09:23] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000028.root for sample zee
 [Sun, 15 Mar 2026 21:09:23] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000046.root for sample zee
 [Sun, 15 Mar 2026 21:09:23] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000024.root for sample zee
 [Sun, 15 Mar 2026 21:09:24] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000065.root for sample zee
 [Sun, 15 Mar 2026 21:09:24] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000031.root for sample zee
 [Sun, 15 Mar 2026 21:09:24] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000034.root for sample zee
 [Sun, 15 Mar 2026 21:09:24] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000062.root for sample zee
 [Sun, 15 Mar 2026 21:09:24] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000066.root for sample zee
 [Sun, 15 Mar 2026 21:09:25] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000049.root for sample zee
 [Sun, 15 Mar 2026 21:09:25] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000040.root for sample zee
 [Sun, 15 Mar 2026 21:09:25] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000041.root for sample zee
 [Sun, 15 Mar 2026 21:09:25] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000039.root for sample zee
 [Sun, 15 Mar 2026 21:09:25] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000042.root for sample zee
 [Sun, 15 Mar 2026 21:09:25] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000067.root for sample zee

Processing Batch 69 (Rows 7010336 to 7111324)

 [Sun, 15 Mar 2026 21:09:26] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000018.root for sample zee
 [Sun, 15 Mar 2026 21:09:27] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000021.root for sample zee
 [Sun, 15 Mar 2026 21:09:27] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000036.root for sample zee
 [Sun, 15 Mar 2026 21:09:27] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000061.root for sample zee
 [Sun, 15 Mar 2026 21:09:27] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000043.root for sample zee
 [Sun, 15 Mar 2026 21:09:27] INFO Reading /tmp/tmpjwn8dkmw/output.35439375._000026.root for sample zee
 [Sun, 15 Mar 2026 21:09:27] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000018.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:28] INFO Reading /tmp/tmp173pkqdl/output.35439375._000456.root for sample zee
 [Sun, 15 Mar 2026 21:09:28] INFO Reading /tmp/tmp173pkqdl/output.35439375._000465.root for sample zee
 [Sun, 15 Mar 2026 21:09:28] INFO Reading /tmp/tmp173pkqdl/output.35439375._000464.root for sample zee
 [Sun, 15 Mar 2026 21:09:28] INFO Reading /tmp/tmp173pkqdl/output.35439375._000470.root for sample zee
 [Sun, 15 Mar 2026 21:09:28] INFO Reading /tmp/tmp173pkqdl/output.35439375._000468.root for sample zee
 [Sun, 15 Mar 2026 21:09:29] INFO Reading /tmp/tmp173pkqdl/output.35439375._000454.root for sample zee
 [Sun, 15 Mar 2026 21:09:29] INFO Reading /tmp/tmp173pkqdl/output.35439375._000471.root for sample zee
 [Sun, 15 Mar 2026 21:09:29] INFO Reading /tmp/tmp173pkqdl/output.35439375._000455.root for sample zee
 [Sun, 15 Mar 2026 21:09:29] INFO Reading /tmp/tmp173pkqdl/output.35439375._000473.root for sample zee
 [Sun, 15 Mar 2026 21:09:29] INFO Reading /tmp/tmp173pkqdl/output.35439375._000474.root for sample zee
 [Sun, 15 Mar 2026 21:09:29] INFO Reading /tmp/tmp173pkqdl/output.35439375._000462.root for sample zee
 [Sun, 15 Mar 2026 21:09:30] INFO Reading /tmp/tmp173pkqdl/output.35439375._000453.root for sample zee
 [Sun, 15 Mar 2026 21:09:30] INFO Reading /tmp/tmp173pkqdl/output.35439375._000466.root for sample zee
 [Sun, 15 Mar 2026 21:09:30] INFO Reading /tmp/tmp173pkqdl/output.35439375._000458.root for sample zee
 [Sun, 15 Mar 2026 21:09:30] INFO Reading /tmp/tmp173pkqdl/output.35439375._000450.root for sample zee
 [Sun, 15 Mar 2026 21:09:30] INFO Reading /tmp/tmp173pkqdl/output.35439375._000460.root for sample zee
 [Sun, 15 Mar 2026 21:09:30] INFO Reading /tmp/tmp173pkqdl/output.35439375._000472.root for sample zee

Processing Batch 70 (Rows 7111324 to 7212137)

 [Sun, 15 Mar 2026 21:09:31] INFO Reading /tmp/tmp173pkqdl/output.35439375._000461.root for sample zee
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000019.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /tmp/tmppdzxw0ti/output.35439375._000502.root for sample zee
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000020.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /tmp/tmpk4n4k4oy/output.35439375._000498.root for sample zee
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000021.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /tmp/tmpgfm7pi0u/output.35439375._000503.root for sample zee
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000022.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /tmp/tmpfpm93ndd/output.35439375._000497.root for sample zee
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000023.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:32] INFO Reading /tmp/tmpqlejag7i/output.35439375._000501.root for sample zee
 [Sun, 15 Mar 2026 21:09:33] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000024.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:33] INFO Reading /tmp/tmp3mxhnuk7/output.35439375._000499.root for sample zee
 [Sun, 15 Mar 2026 21:09:33] INFO Reading /media/lucasbanunes/KINGSTON/data/cern/global-ringer/datasets/mc21_isabela_qt_2sigma_restriction/source/signal/user.isilvafe.mc21_13p6TeV.Zee.AOD.r14136_2sigma_constraint_26.10.23_EXT0.tap_zee_2sigma_5M_XYZ.root.tgz/user.isilvafe.35439375._000025.XYZ.root.tgz for sample zee
/tmp/ipykernel_986425/4247997998.py:12: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=temp_dir_path)
 [Sun, 15 Mar 2026 21:09:33] INFO Reading /tmp/tmpa0_47h8w/output.35439375._000500.root for sample zee

Processing Batch 71 (Rows 7212137 to 7247099)

# Validate Dataset

In [9]:
output_path_glob = output_dir / 'data_*.parquet'

## Check Target

In [19]:
target_query = f"""
SELECT
    COALESCE(CAST(target AS VARCHAR), 'NULL') AS value,
    COUNT(*) as count
FROM read_parquet('{str(output_path_glob)}')
GROUP BY target
ORDER BY target ASC;
"""

In [20]:
with duckdb.connect(':memory:') as conn:
    df = conn.execute(target_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
# df.value_counts(dropna=False)
df

  value    count
0     0  2177107
1     1  5069992

## Check ID

In [21]:
id_query = f"""
SELECT
    COALESCE(CAST(id AS VARCHAR), 'NULL') AS value,
    COUNT(*) as count
FROM read_parquet('{str(output_path_glob)}')
GROUP BY id
ORDER BY id ASC;
"""

In [22]:
with duckdb.connect(':memory:') as conn:
    df = conn.execute(id_query).fetch_arrow_table().to_pandas(types_mapper=pd.ArrowDtype)
# df.value_counts(dropna=False)
df

           value  count
0              0      1
1              1      1
2              2      1
3              3      1
4              4      1
...          ...    ...
7247094  7247094      1
7247095  7247095      1
7247096  7247096      1
7247097  7247097      1
7247098  7247098      1

[7247099 rows x 2 columns]

In [23]:
df[df['count'] != 1]

Empty DataFrame
Columns: [value, count]
Index: []